[[GMP]]
arch = "aarch64"
git-tree-sha1 = "8ac4d6609f9aeafa68dad446622357697c388783"
os = "macos"

    [[GMP.download]]
    sha256 = "3cd51f835bbacf7b27427521a9126668006322d5308d8154a9122a52fee5eecf"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3fa2fc12bddfdba84b24915395d190b572f383b"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "f0c022331f4470f285ed0b20e5237754255f13f119a9a6d932399f05e8262db5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa547ae41811ab8e80f7154be95e4c3b5e7b6807"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "e62389b852bce17ae15aa6be2712729aa1c207e4e8b289a9f02917e8bfdd04a2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd0a0292e6f8e574539fa3729345b371600e8a2b"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "cc8c1c43ed9f665bb0bd6d5166b4b571eabc81c0ca50b214a8c4be7005e86af0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d65a6f7e917d534a562ec07126a18b8ed39b592"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "0e38f39c7414e07c4171dceb082cbf500f8a61cda3674ae166f63657b30d112e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f6be7c5bc7133d2f5594b8b465be40ab5ab3bc9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "dec123ca9203216f7c21e4d00c741bbb1ac51680f499f2790a62767882e54308"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75bfaaef36e9579f7e6207f94d7af8dc1e68c080"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "f5f8c35225d7a0eac1fe7dc806eb3e031fe3d3103e73c0c57a90911ec8d47947"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48853276469ccbb488c01157e152878b67cbb77d"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "05639a430f6b569f4127bfe9107e5fa2611dc8a7bec0ca1c6df02f7ea605a193"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f0b0b83799ecd93f9937efbf5f493dbf254d8c9"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "bb5d4b3fbb50b75a79dce139a3fa3329bac112d1722b27b36ee7fa8264ce90a8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3df599eae198596aff6e6e4247f1ad425b98b97e"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a183632e46d89072913f3120c004123f9f52b0c52548d91ad3bb33419534cfee"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da32a83a78b7165243d0b134aecc1761127d9afa"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c417bd9d838264c9ea54fe5cbc4d327d8b59b969945db8ba8f433ebacff0d56a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3153e8356268214b4116493d67227bdd55c794f2"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "789bb362342e82e968803ff0de50235ed03be2904b55e93994609141bc2032f2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7741c9623fee466b22ac6b346f004378ad4a89ea"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "004cfdb557ad4be67343e5c21c99ba8ae8610df999e64b89a7660b13eed5f161"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f6916361f02e67976513e831fca7037743b6157"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "e1aba8b7c79261ea0c50b0b638b6f9a0226860406cb8dc9d4aa66f2c858dbfcb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b06eb0ff40c419629cd56538362cc31ab163b518"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "be239a3a1249dd76f9457018244ba1a45108d2601eb824d67b85fe4df23c4565"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8e12696f71dfa9e780e3b9f9b6834518ba09b46"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "5f031edadf0a1cecd854eb2e11af807654a4f75efa839116e403bc56f93274f7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d1643f790078fd4ce66623b3ff3e42a9f96a769"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "8630f2980153b47834a10f5f71c830f0162a06fe2ec37f7372c9e43871aef5d8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42706460c0b4bcd536dd2af9edac39398152ddaa"
os = "windows"

    [[GMP.download]]
    sha256 = "c7f43caa25c7c83c5c8869adfec5ed809da108e699aa477f993e48b0e9d6da50"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "898801fe5a710c59a1b99f5b4ba58113d0f77406"
os = "windows"

    [[GMP.download]]
    sha256 = "052f8fc43b4bc07d45df09e668a67a2735f2d89177fe011de374b0da23161d88"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "538949cbf952c8305ef7c91ec1e25c8bbbd156d4"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "eaef9ae5b64187c7c31dcf7f4bbd05b4b2b223a842a53d638787109a1705293b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bcfb00c039078c3af58efb463be3f90eb50e132"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8bb8033bb08a967bee0225caa7f67600f6d6c798de5753d9fc95944dcc27d77d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "f93500599046996f896b88870baf9ca1a226d4e7"
os = "macos"

    [[GMP.download]]
    sha256 = "605c1b3157d32af6d6e9e3bffb6accb40720acbf43d4bd1d4505b5f41e40e713"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d1179281c4931937bb1c3ae769b23253bf50cf2"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ce3ab5526dc93bf9ef45a2b3e046ff530e4b1dea2044895fffc0e351cbae198f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c1ccfbe42509592165bbefcf987823196c06cee"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "991de46d96ca8200febfbbf0906c1024d5606bdc9fdade0eb10552e406dacc49"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa77bbddf0480f800d87ff01f55fab8139ef5c99"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "a6eb6bc2b466358563dfc708d890dcc3c431011a3c07cc5c58f9cdafa7b2506a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24782cc3263b258b98b3c68d37b3c6c7115d4c80"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "7f15d705ba1a1e8332368640a7018414cd47addbf43cc75dad16a001c16a80b0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "d4f64892ffb143b7585b404e0667417c34907be3"
os = "freebsd"

    [[GMP.download]]
    sha256 = "fef7176a45e5e0b1ad527f75b260fc318d462f5c6ce5c75705b8214ed3311156"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "656dbe691cbde06bea2878234b0758a3660fbab2"
os = "windows"

    [[GMP.download]]
    sha256 = "8ba5ec17c0349502d57ea3a20789da034111e8e7aa0e98c9487bf21d3a703f2a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ad6db9f60b09550844108516027e16626ebbde2"
os = "windows"

    [[GMP.download]]
    sha256 = "de5ec038cb8e4acd876ac71c296e8ba713593f2aac4191afa59b70d1799949be"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+7/GMP.v6.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
