[[GMP]]
arch = "x86_64"
git-tree-sha1 = "65367f94a67d219b1256ea9fdc17e6f733530264"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8dfe1b4f75b0d26b97bdb28a114b99c3eccacbdc697f08da0ec3eab212baa169"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "efb54877a913b47aa4278931454d012a61cb44a2"
os = "macos"

    [[GMP.download]]
    sha256 = "56ea1757b2db34b3c80eeae9207ff8e4d52c37073eb5cbfebea18aeef69ef2d7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "5339d3e46641716e67642826accde1ffa4d26422"
os = "windows"

    [[GMP.download]]
    sha256 = "81184d406de75876b2c6faa9867c8e214d5d344cde4a61af8e9129ef85bacdf8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "efabdfd066948379eb4ce09251ef5cb9230ce849"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "27d6ae9f6f0c20730ee79562f9f9264ed94fabdcd372fbea2d4f47958aba49e9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "65f72ad147fd51a680b5b7ecb49975031e291977"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "e8999417ddb3b263f7d7279aea446010656839ca807aea785ae596074c7a087b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "80436b2473428705c62465ef01ca1bb1f134c6df"
os = "windows"

    [[GMP.download]]
    sha256 = "d37ffc11fbfc301ac3a8df368dec4044117653a9560a865e0cd6f0c35c1babe4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "969935959e19830f7d2427ffba5bd13629e865a1"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "94369101433ee9eb033d5afba14e5d1fadb30c7849f8a99f9a18b4dc3408709a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "12148d98b1dbbcfc30251ea898ac8e6328290f9a"
os = "freebsd"

    [[GMP.download]]
    sha256 = "933782ef39cb10a3c5b38e85ee912d79dbed3ebcc04458c5c74c283c518c77cb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "3c2afd14c262b0ebcdbc7f124e5699ae9ed6a86a"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "222bc95231e3057301b3643ee7c8a7c3c832549cc2a0d06f999ecdc58d1941af"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "e7af069465a45f702698a4b8ebee0f41c942f152"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "012560f75b7ce030af02610b45ce80444a0c84d6062936d1073011a9d9d12bdb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "2661748afc3a71d7f035bf25b0b1239efa4a40c3"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "75f8b5921a4811da7efe275c52b9dc60bd82b65678cb77794ef73df49257953d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "0d9e5998774636e1f4db01782571c302d1638f6d"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "62550dc4bf266920c659ae3559f1d0cda90e0a54b605211e5354046894fe5f42"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "7a706ec2345664222b476585a998645519595d84"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a2637252021a1a35a4cfc6e91a7c648909bd415bb44a26ed40bed8eef1bd4fe2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
