[[GMP]]
arch = "aarch64"
git-tree-sha1 = "497304df4d78297cdc1ba7ae006be2a40db6601e"
os = "macos"

    [[GMP.download]]
    sha256 = "4bcbeeb7f30300a0eadb5417688af38ae21c96cda37b3702d1d971b2f7bdbad7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a631dd6ebf53e7b2f35b2b1d9134ea32c379c464"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ab9deae1cbf6f60e980e9491ed472da94f0eb326b170b4e279b116774000178f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "500892c36200d44e964a9fb6ca916a286471e4c3"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b9d9e287a8dcf7891d120db996d57fb59212047ac25eddee8f8a7361bf2c07bc"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c4986560eb11777c94e5f9f0ccffda3c66e526c"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "a6f88c83f9131fc9fbb650428fab0a5ff68cd1dbc036e61dd35dde92a78328ae"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c08399d7ef2e6885e0f3ea02dd556e6ece46ff6"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "587d9f56d7a13e6e7f9d8bd3336a4a0426c3ed2f79315b6df7c6bf4ec8f9863c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e25d50258fec8f38cc891e9cab7fafd7972fc623"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "90bb7a026d9ce20c290ac0bf8e2230a44212667a1471546a45448dab0c2b6ba3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c25161cb37caddb879a25928e21b9bde4db53e6f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "929a714cdd4c7d30abeb67e84be8d28097da86e99cab563a6a136b8991ecbb84"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e318e2725420cf7c5d6428b5644da5303b41773"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "7668799db80b79675b8a50ee634375728983a01ec3f1e427fad8f8e4d25c0a53"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d14ec254442d14f9528fa1279870b604b91fedeb"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "5776c632ddef7cee0b241242b6aea6c268ce990373adeb2cdc24a6ccd09d4f74"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cad76014c1dc7d5be726101bbcd36e1c80f8dc0"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a3219685656bc006131673c9d109e3362331d6dc24edb48f6b091ff889aec356"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2729aa77564657ca49d48cbcfa35131b92e9f00"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "cd333b537e4d81517d25c09a6a9f8dcc1b36e2ceeae1baa796d286eea79666ab"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ac692145a3162c5bcf26c0b4e94f0b34e62a8e6"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "22c5535a6d5ed0178c0bb73d14a03e6889eda5405c70486217313b52f9193934"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12595bf003ee3352a51dc87df8f8a59e2b83a478"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "95589274a9a5a84e0dbcb1a12695082b277d1c65d7b6b3cccf4bded81da4eb86"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2aba8c280809a2cf527ae4af5246d6cc839bb465"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "38746772a4953d2f643e71fe07272090f01983ac6158d9e202381af7d2fbcdc2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bee6c76253512fb425e2c1ab618eed36dc5add93"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "eb98d6e3a5947218e044c57725d3239aa7e5b830c77d9e5b29a12417d4df9a0b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d8600d096f87e0d7ddb752dd04e447a4e0d5436"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ccc78b0769b927d690b953107aa882e8dd4ec53f3d0c94b434bb2c1a9c063bc8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d49b1337aec662948e9d533d5ea71679843958c0"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "6ed1f4aea8e9c6349f6a294b5d020c850ca173f1e88b428ac6a558c4f5472605"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12ea5cee22b6ee6d480987dc7392a5f3e61c2926"
os = "windows"

    [[GMP.download]]
    sha256 = "596307e3407c9d007656f553378217e01631e663933901e8cbe40f7c8573caed"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1898fee3a1123f3da354350ab0734a51a480b229"
os = "windows"

    [[GMP.download]]
    sha256 = "299373667eca54e34b1a2c07fbf185b58fcd8ccd23822501fe396b826f2258ee"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fa30e4036a23e3b6c1ae480275e51980fd97789"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "666313d77c27a999262a7cb454a122d82fce993080c7a7a3d6708b28732286e0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e27061b49bc2371875a1ce61df2e484becbf875a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c807c71c96a470e2f35c05447d9fe020b53d576ca6e5c366d0bc4754f888b0cb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "888b61d7725cc172f8bfc6ce2aee49546fd176fd"
os = "macos"

    [[GMP.download]]
    sha256 = "b70037fbb1c740655cfd1c8bcca9f49cc0c77735fb611afd1af2b3e2001b1ecc"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf7595c26d5a673f22351bdb0fdd6b2fa000d94c"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "3f9118dbcf54a0beb20acdafc389b7c73aa1581426534de3a142fab28563bb2f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a00b49558b2899cd70a789945e05d41723e3931"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "caa455e556daed92485e3d38c5f92ae05acf49c1c629bb8c11d6b697fa90116a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "356709685133acd7159f3a64175817abac3324d8"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "539f0c154992fe1062ddb823ee1f90bf6b7203f15e22339f9b6bcc9d62117702"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbabd83e7c0939e4d4ca44fc2d53be607fe5a673"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "8b514d97000267c290b26d829e192f89b14e38edf025d2f99863e982f35ca9a4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "4992514329c33c482d7ecbb9f45e141e01d5064c"
os = "freebsd"

    [[GMP.download]]
    sha256 = "d3e21d2b27a56d591fe8265ea34b517eae04b6ec8c41566523da8a7899193642"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bcc1e1e12c2cac2211330d66b54a937bf043ba6"
os = "windows"

    [[GMP.download]]
    sha256 = "be54f1f45788d640c27c4a3c77fe5db7ba83b3033cbd09a0abda36fa9a4216c6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a452331173dd8b4dcefd14b73218e3535b347d7c"
os = "windows"

    [[GMP.download]]
    sha256 = "e3845410d9b25f00833e3a7f90bb150d85651816eb0295f64545a1aee0aa39f3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+5/GMP.v6.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
