[[GMP]]
arch = "x86_64"
git-tree-sha1 = "065a6c0e71c9870ee6d24bd3d52e240d29dc06ba"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "bb8527e9dbafde024b7e2720e291d8d518952d05fdaadd7e115a245f2918ab65"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "8662473d0f7e6e33cb8049d42aacacf485fa99ac"
os = "macos"

    [[GMP.download]]
    sha256 = "89086868ccbdb13cecae37c03dd4a80c6185f122858344db2ce9ad114a561535"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "bb9b5f83923d464541b7d24f57f373ab2c213977"
os = "windows"

    [[GMP.download]]
    sha256 = "cd26aec4a58a53957fb935363b94df30c491f3194c9415f861873c7bbf6fd502"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "f227026ef1ab626b69fc36c4453eee85bdc09f62"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "218c523f990f1aba51f332373ab899cd0f4b65d3a3abed232df11ca52a303488"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "9b8b9a94c54a7e712f27689ff1280869f39163c9"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "384cc26bd941839beb93918ac7379131e113a2e972f6f764b801c6f7b3683bfc"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "f90ec67611045af8dfd4fd550ad3e0c7d6a241f7"
os = "windows"

    [[GMP.download]]
    sha256 = "0cff5c5d6bf50654ce0d9cc287a1f2aab12223b65943ebca1e6ef8d5c1fbb187"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "6de7a79808eeba302aea4958b3da56c291659397"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b51d91e149ebcf13176db407bac17181ab8d1024935a9b3f7a4ab94dd1100192"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "e08d27e85e91136c361cbcff455916e0f6e58a4e"
os = "freebsd"

    [[GMP.download]]
    sha256 = "5c8d4ff5edf37fe9d8b55928335780135ebd97de385b3cd86948784cba9f2321"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "ab0cd552aee489c33915d700da931cc5b7165f19"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "7c5faccc32e355af222c972ef3814f5dc8eb56153c65e6076cab5edd5b65d96b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "37779c5aab992e6894918d7eaed8e2b3ccfa9495"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d40cc5360f5f482d83e3c9d0470ef940757256eebc1edbe50f7be3d2e6591f36"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "2dd93ed217590a2a2bbc7999f3041cd1bd4db3d6"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8937433e50ca6013d72e28d56e6085b6b7a7241e6b46bf90069d5ff6e777ddca"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "588b5e1a76eb07c0b5c297c5c9504e7e0adc95bc"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "99349ae3b363a6dac220cebc8ba125029a3e96021b72764f15d7dc87e8f9317c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "dbfac28852c975a26c0cfb420075d8ef202d6093"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "d08743a43e4f9bac30805aa9f2ecad4b7d7712ddf6124e26c3e24ee456b715f4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
