[[GMP]]
arch = "aarch64"
git-tree-sha1 = "a0426b197d46c26ede07161cc220d0b595cb2819"
os = "macos"

    [[GMP.download]]
    sha256 = "7bbb5922f4fdf26da24a38a5dd827784fca47748964c4c8b3f7797786a54efd0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d5bf9d182eb5c8ffd69bbd49d0b0e4fe474f42c"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "3b17aa24c0e03f68a7556ac488fd174c98a31b5fa69f9699c30af92cdddfeb61"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e4d313ad97bd1c63d47a9374093ab58056ac68a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "343b1876b79eaf1cef261a8e3c23f4ddc3edac231a0f99413fb34b5a95436d8f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bf0d4d07e054c693ed3bca806e8508891955e40"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ac95df64bdc587ff470be664606849ab5837c298961b9030b4fe995ab0fcecb1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b2a7b335b4991fc60523f26fa357e937e0af710"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ffa36b7c176f78f30eb6a6f5752dc98977c7dd0bc0aeee81c537d439a285de75"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c410fdc4e66c83bef37ab8a07d90242b3916fc8"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "d38c67af40ebfd0dec932632d63bc79f9534ec8fd9b33230188455b2ba681aa7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b0a9188ddada28359b11866d93a550ef6cb481f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "f893444988a0b9a0534a18c3370355a0c82304f51d97244227748a5fc11bc1d1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d5fb86546a5b9c2c5429fbf55deaba5285245fe"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "7142239a750a50d12458164abd3241469d01e4383e62212ed52ce73fe0e1af4f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "283c7b94b0cdef786d290d87c2dc767be646819a"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "acfd20a8426619220eb181caad4d94d6c55ac5c994702cd6b8fc99ce3f06eb5d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1a4769589911552efd87871dc70eea2651ebadb0"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "70b42f562a25a89d9ce18afd9d63e02ca2119aad900cb93fcc4cb31581126def"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "252663bd6f30ab67e65ff955a285e624819cef0e"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fc4054bc05456e02b69c83cc5971276f891902d11cc22ab9f64fb701b6fec26e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6558e9cc3604b828adc0a6ea6a7fe6323e8a0c4f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "b62313fb67e5e818827e05b99815e3055966c01630980627b7a68aa0cab01437"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1df7a33eaa1ac0a6ccdab56a24c23904af8126b7"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "e779adc0190217e4caeeb023ee4aca92448b7958b1bc4e34b2c1a7193b6fc9a3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa4e52a2e425d104614a2c0b64043fd097402b0b"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "9d7072488e4fd0954d034dcce1feedb9d879d79f1027b977f43b759a8c2e5619"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05cd17220ae306b386e825306d865f4e6496778e"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "db858c7ba4c33bb466fd56f3085d7f6d07cbd33d36057b2fcf99849a017091cc"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9aa823560182c694ef0d6f3f600dca3507178160"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "fd4a7ea232b3961b86b19d01281a1623e45f87508c7844fa49f0175c7feb2418"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17b27a2d9e1d0c92a466febad9ae56205b4e98c0"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "8911b39cdba2773a1fc217352039fb6849a859e389b6ad21b327260ac770915b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f91fe1c7d23e37a41b3333af0d9126d5471dabee"
os = "windows"

    [[GMP.download]]
    sha256 = "2abdeb8b0fdd65d55adb6b73ec030b1a0ccbc377d11b741653375048141a35a8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8178a782828152d7d5460a3b0891c236e24ebbff"
os = "windows"

    [[GMP.download]]
    sha256 = "1ae0991afe1e9ac59ad87bade1b268b36f30d3ec0f26b494e0760771bcd8c9eb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ef31c629414642f822cbe83929f8c0dfce0becf"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "f9bdef0a894296f9e3db1d7059bf20ffdd7d53864d09e147d75ea5d9215941d7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8db455474798e7324c4d3dd5e565cb9ea9c32212"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "1d5e200e6ad86e85c21b41b5ed0d80f4f0dfdaa134fad567ef4ccc119a33521d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "15e23665ed0ce1e50e5f565a175d0b860175ef3e"
os = "macos"

    [[GMP.download]]
    sha256 = "8b92a48ae82ac027f00878f5ba796041f0af296fa7b7427562fb5d9dcb69ab34"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94d3761188238e158d07946616727af3d5599d30"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "db30bb90a3aa66686eddc343e1d052eaffb769378a3c09bbaeb0301ad406c30d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d39aea8e1252cd3fb9cfaa90a4dbbfe1c31bf74"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "564d79a116780881ef49d23d652f15701a940d20610dc6aada85552256073633"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "5304e90b95369905671384322b68d85d114f6ab6"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[GMP.download]]
    sha256 = "480288b4ff4c515f8900b35b2a1fac8684d9e7e1c5a6884dba08de2dacf9e77b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6ebc462279bbaf3e01927441c7f1fe0c2f58465"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d8b93b2a1c96b32bbccac2503e08c4e18c667f3ae1882be3869fb5e68d686a4b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ff5c5ae9cabf320b5766dbacc57a961f39df3b2"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "5ce91ac1c4280f71bcfbdad623fb2cc2e8fa2a30218ddc0c9b021aae53d1bc88"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "9f516121a835a7af7f73f6000fafc0b8651864b8"
os = "freebsd"

    [[GMP.download]]
    sha256 = "58883962204f380a437651fc9f7919c879e9695e31385351de9f0537756f326d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aaa34a506cf498209430732db8809b6eaa88639b"
os = "windows"

    [[GMP.download]]
    sha256 = "f66318a144a15de7be82f448a25e61f12d3790796e91bee5e0d0c34b261d8981"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1899dae17082b3303b2f6a774f4a7bbb5da5b303"
os = "windows"

    [[GMP.download]]
    sha256 = "383a2296356466b3b411456b7e5b061879d8723bd5f45591cbbaf435a318424a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+3/GMP.v6.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
