[[GMP]]
arch = "aarch64"
git-tree-sha1 = "4ae7d72dbbd301daee90a6fff23184e949c2a2f1"
os = "macos"

    [[GMP.download]]
    sha256 = "264f0d9c565e6a060c697608f11d5725fe29df1c3893bd29aee1a98b281f2ef7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bd64e501e3f4d9704cc670d8eda41d83bff5b2a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "4e298726090625d88e67e5f68bb1b47eead6a474316f2489935a2c06692dbbab"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99ac4e744271796359443bc65f5c4f554a4e0f51"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "9bc8aa666827c4aa4fcb6a6e92f801dccb248ca6f661c6572c8627076f189bd7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ed57747c25e7722bd0c992e90c157f65d1929c6"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "4e07ee0d02c63260d829c06fd1133acf62443f1fc7646e59b566320b15edad9f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0d437bbf6c634ae10bc0d32e748d3904f75e9f9"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "8e41ec48402271d954d88c61511d73911895850e374576aabb70c21965e21c6f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15dca6bd89ab9995d14a7342b4f827dfe0cba5e6"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "9eed356fcb98f63b5b7561f3714f4f513786f17142b8825cd015a46ad50e10fa"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71c8e45d125b9865ac7e7fb3e993bf8172e3ef8d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c3a218d492faf6a7370855da0f03b3dd2c87ec8fb44d702efdcda78b7892233f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b076cb3cacdb9611755dc6a669b14257437933ad"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "869fedd4a3e730d79af76b0157a45b895b84594e10c559fabaac2f3a567c88f8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72fb46349be3d63e9dbeaac200ad07e441ba6072"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "9c3351da8d8b6b125da5eacaf08a386651aa86f44e561aafcd75fbc082a20f4e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d2133c0441746e339ff8ae5496d85aea6b89b9d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "44b5382beeaf7cf7c3dc42fb1cde808a03ee507c9a28c5a953ebd9140513db77"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13ee2c66094d1f30779fad270a63a21d842c4ec3"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "0afcc6b60162ec43bb62f0b8d573d1bdf2d50e6dc51874eff98553480f067d3b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "397eca53445c3aaf065c153c65e153a37c600437"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "0a5e30f4452bae57a86cb1c90353577860046d871015fd2e19681a3ae7289dd3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c697199da5e6a4086b2beffc58929a8d521cfb1"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "bf7c16bd7df7026883611f7181501562ba1ec377a0451a1eb699968e7e198c47"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cc76181bcca4dba88273973213bba2e57b88de0"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "14f5608c3970da82033f5eda27f6f3f407680dec8d7a1389d904ef8058ce6fe3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f49882ea75b995d127d4048891bbb6c54cb20009"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "11794ad20d0ce76e7576cba0eec4082bb3de74f4609af7b445cdbcceb49ebf53"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "955feedb38e626e567e8bde3527f785fcf221483"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "e1beb176ec45e11cfa4d7e31a84756ee33e9888671a414de4451feb98016017c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2daf74735534338e9cc1a4e2def93a1503457e3"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ae5560009b64284c733cd30a579d7a6d6733c2aca43724ecfbe9ecfde840657a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9add258eb310074bed88fb0718da933ff3eff5f2"
os = "windows"

    [[GMP.download]]
    sha256 = "a9a331f22a4d289ce164841a0e8f6e8a4de8cc036e143a23f9a04eb81cc2a1ec"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "820507a17dbb3239b67b50c89117f5d55afd6ef5"
os = "windows"

    [[GMP.download]]
    sha256 = "8d767ff9c2359d0629d25471bf75fba33a862275f7ffdb86cd92fde0811214ed"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fcb809dccff63a12472f8869ce0f51a4a7ec0c4"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8ffe14ebd0d0a161a5c936d1a53a79d373adfb520de15cf357d9b73dc43802bb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e989b34f296f1b5d3b051d145d9183521318e2c9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "7e06b05a28ab3192d673dce4fed411dc22026db9b451da72b45ded78c17adc8d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "a294f86becad54e568856ad4c9a237fe9e942f54"
os = "macos"

    [[GMP.download]]
    sha256 = "de5a828b391244c3d42ea023122e8e3c7a627e2ae81747afed44d7f28eabd7f5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5efa713e46a132d0b356a03574bd0f8902c8fb4f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b680d8c1a8e45bd7a11c04c88929d27ad1a5e2168f299eb594936fca89cc25d1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a91250b4cc0a611bb15c2b8a8e4c253d613d511"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "201de5010262a943c884d70cc59e67f837cc886cf64bda94ce428e889f78d358"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8e6abf20b25cf06913256d00bf44a78961a03ec"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "a4715a56e585fc9d49165ce4109919aee5ccd60a7a29711ea2affa08dd46dab2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0468bd98f0807dd7d09c33ed66791e1633d6493b"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "f3a83aa06a592a6cc1d7f7457f9c1d081a2c4104a0dd10982775041c0e31a81f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "46cbc5a34c1a046a34b8deeb542478b7950d2b30"
os = "freebsd"

    [[GMP.download]]
    sha256 = "330d31c2a94245a1fce81c5a013c630186e79ad9915ce7fe29fee1b190ad2a40"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbf34f0cedf9d5490d9d7c6b601f628e4b73aee9"
os = "windows"

    [[GMP.download]]
    sha256 = "ff583be259403cd1ab1a0bc75ccef60af917929d55334aba45cbd4f45d4d850b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0e37426c0940d031e2322ef95c7d17dc8b4646d"
os = "windows"

    [[GMP.download]]
    sha256 = "0c4f88a1ca99e4614281463669e107124fc898f63059a0219b8d686c1c8bb033"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+0/GMP.v6.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
