[[GMP]]
arch = "aarch64"
git-tree-sha1 = "8d0d8f241aa20d8c3874d5bd523b55c9148b0820"
os = "macos"

    [[GMP.download]]
    sha256 = "b6da91236bf90bccd7b14663bc6c6cf6e09aaffb577559cb1493fb02a07a9600"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bb260496f5bdc20241149378b1bb402186b41ff"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "d42d2a78a1b1c95f10d3b2512d3a2e275e4c7028a873093868da8ecbac2da682"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45edf6327575efbbce9b4a455cbb57c155effb0f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a6a159f3f4f6e1e79c6af19ab446257f798efd066c5b2ab3ea2c8db68a0f18bc"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab67845a7c19ffb874965e18e25c3d5fe609b006"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "07607c305c11e163e8d2db00707bfaafeb58f213b866ff6aea4e36c40cc850f2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bff6dbadf401034c7eb0285d543e36b8f173707e"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "5f6aa3b217ba82e1f9fa73a96b06d07fe64159068bd17093d87a5c1a5571a26d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "a9d0608ce8129c0dabf290b6795306974717ae9d"
os = "freebsd"

    [[GMP.download]]
    sha256 = "b3702c0eebc1f2d7a3fa133419fd446ed1e4a6aad65bf817fbca76a4a54141f5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.aarch64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10dff2cd5267d559a8696b5b271b5549edde1e97"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "34c96d81a6680a4459e37a22c09e2f9667b3982fd323e44250dde50275799e28"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "091e4225bc364e86ff37bc088ef56c745afb2510"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "eee16a11eb3a53951fc8ffbf69b5115f4ee981761a0b6426a23773ff6ed763b0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9da2753b70301afcbfb51d1d95e492e773662877"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "36161cb38015546ad21b43f6f350c0218b23c066f067d202c4a6fee9369c0f36"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cbf05ec2c2243a753ed665d431122611fe2b18b"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "45397d33ada80b364e06f171be1c0aa0fc57aaf15230591a4cee522507a9206d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ca603211b43fa3fb979f2a7890b2806e03249ce"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "3c9c353f4953bdc853eb2743ea9c8f629a658b1dc072962858857c05571de9e9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "732d458037a8589b0e6497a0621fd4e00a33c9b5"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "e949f0f2dfa2a5a9881e6f4d81d4ba509098966c48a525a78904749023d4f3b1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18dc781fce0a29c37336bde7c9bd2a35cb2ccdc8"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "23948309e929b71b0de806ae1266a43abc904abb6cdc4a03c2677c474512aa88"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffdb5b251a4b6f775c432bd4b462a7bfed67f116"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "54584a11df4f048b429bd05be456ea44cfce3d2942cd3ae9fca0b9d7347628c9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a45c13e378bb5b8d61991cedd238ec414205d021"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b90f7caf3bc98d8a381c7f72f266f149522e96f962b8d978dfc8571db0dd5684"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "213428d87e4c5e13a61b4e7760362ad6954250e0"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "d7bc19c69ee1fe2832171ed50f571e3bd817268e6818c2ee915a94c395b0a1a2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1785045bb73369e850772293b3aa5b435d598b48"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "9510a85c2dd35454e7e0b37cd6bf35c69b73187f6df6ac69aa7dd50c5d395398"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "691758e68edce5e8242c73c556094d5ba4032463"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "1d4175563f725268aab2504013adbd6017af82b9d09a2e532e2bf9fcd1685013"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e4ebe996f6df25aab11829ede701b86593455de"
os = "windows"

    [[GMP.download]]
    sha256 = "1e0fffa7891a1fe32d7267f98d24601de15112dfd80cca8c3d033880af03e02c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9719fae7f0523828f4fae3ec1204a962d583877d"
os = "windows"

    [[GMP.download]]
    sha256 = "e01e82315831aad785cabb91deecf6b25442b6229ea077da18969b998a83a7de"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0045f143390793bb108eee3e157a695e70d3817"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ae58c9b17fbceb459607f4bd3d19a2292ff7dd60541d9cbb58187bef78203975"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c490836adf419b7c0a04db6ce0002c351ebe0075"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c47825e55c671de055c0e61d289d463230834edfc3920a67ef62eb4b8527e058"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "76633a301a266cd900bd12ad31da4d924f82b188"
os = "macos"

    [[GMP.download]]
    sha256 = "bc66d1afc0ab8827cac2203055420a87314969deb2cf48ea9fa86b000053738c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40fb11da499d6a636af631aa2e49f012f9001f8a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "574fe1437b87bc995ab10ca6ea7a03028b94b65698de74ca420baa39a549caa0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7470e426238b2c873f373c05f66ae7cb929b9180"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "49763d4a4091e3ce026176a7edb4c392d9c104d94845072d389066ee3208d803"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "661f881d35460fd0bf20d8d16573eba7a2d29e57"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[GMP.download]]
    sha256 = "0661e23ba08a1849473f24f3016e25c3acf16abca3dda73db7171c1cbd7f1321"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.x86_64-linux-gnu-cxx11-sanitize+memory.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f62a19b53f4b1b5152d2cfa390d0941afb064973"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "9d0227a041d02dc5907d048fb8f16314a8a17eb2a6ef1e086a3d312d78efbc83"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "620643787a840bb90ef58d4b00e5af0b196be188"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "c6b5537a888b1fdd0d2890b3184a4524c5cd3fbdd8d92cc497be413846fc0c7c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "d83fab5cd0e65d42ef43a5f1f01d999646a9e7b1"
os = "freebsd"

    [[GMP.download]]
    sha256 = "8782c91a1f22585169c7d5cba7d976066afe464fad75c6d5a6161bf198afe43d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e84d10f5c707d646febf4bdee7f133cc62665df"
os = "windows"

    [[GMP.download]]
    sha256 = "bf25d64eeafdbabc088cf30380a0e12228dbd685957e9760410d65fe0743ece5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83f9c04fc00db5ab8a178dfbbf7a834c6e4c874d"
os = "windows"

    [[GMP.download]]
    sha256 = "28ac112d9c8934ed9c8332ec4ce71ddbc06f779345611f084217a5490f489b63"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+7/GMP.v6.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
