[[GMP]]
arch = "aarch64"
git-tree-sha1 = "7191e1c7b144366dee4f459cb98eb74f1bd7dc0f"
os = "macos"

    [[GMP.download]]
    sha256 = "f2a5ec7407667cbfa64795ec510d3c53dc8771b3ea04a0f308beb31bed9968ed"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c85669918a5836e5fa189b569ac899aa82357a6"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "be8382e26b0ed68ea8af59817e7f5d1659d82e429607b5d2ef96d71d02d5609a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a32fcdb0ec0bfcde80c4c8342034706d475cfa9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "72853aa5ecc47d181261f652545c2370fb925f82ce182ed57e2c3d0dee63af13"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37cefec44f2cb164cfe4d28ccc87ec676e42e421"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "b3d290927c817b5c2757ba3e24b4f69e92f3621aa5b5d1978573ba18a6c6f0a8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adf23b316089dfed38ee96feaff3148bc56f0868"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "54ad57841f3782d80e8cf91f26e2a74721a86c0dcd6bb9c34bf58743ba224bf0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "4a460820625949b0206615ce89c5a7433e375f54"
os = "freebsd"

    [[GMP.download]]
    sha256 = "c4315d0a2da5361e80ff9fb5f62d49a005514c1f30047408b51da16f338074b6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.aarch64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f48c22985d061f8f4679717e534bb3acb9b88a62"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "7dcf9b911310d35887b69e0623e597d13be3eb94ddac0bd7b7dcad2ded4194bf"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0915d8513b886eb1a85f2f0831688eec26fc4e4b"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "87b5002579329e19978cbf73f64ddaee3a2b87bd07fd532acbf7cf67b646ee42"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d970bf72ba6e8c8f6c6f1a4f8206fda7cad2b618"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "86351aafd0cc06e341c6e86d34062663727b5224ebf2f6c768ae0fe11eb1bd1e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05588f11f050b9ea943d10dab991c935d8962414"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "fc3f2aab266e90207eaf71dfb14b41ae099581b7b2d2ce59650d901706772c23"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "615a829900226f5b1c8fa791bd28d5b95033b28d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "4c3cf4d9c60e40836ae403d5ef0c27378c4692fc059376b27d3660b8b540be89"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9345913b34fdf2797b28f0d9d975459c0cff2c0e"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ba319abdb104046d2c5213d5be7571ca09a24bd845b06cdf3d5859bc3585a537"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dda8b180684f272ec361a15c64536e7687838c6b"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "6d8d363b2204ba17ea58f399d13f0d2cc4d82a839d2e1167a3def321934226d3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd30939bdf3aecaface590f5d07e409b5e4b58c1"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "8a3e8200225f797c249faf7d22603f94854adaaba6d53631c23b9a063c5b9cd3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "855a51f53dcee301386cfa0a62f62ba1e7f8b847"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ccdd81a961eec14a69de01989a137d4bf6c5bea9326dc9dad7296a3f6558b83c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c9d468e7df00ae785c64d8dfd9c1bbba713caf8"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c3fe1a1b300b0d3d69fa04e74a260f1a201d2218102ba2a7d117357ca9083bfe"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "feb6f0bbc6ea3a5856c153205dfe568e80688e6f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "f3b2b0c52e0d48f2ea7de13af0013e5e9a0b7511b0b1d3277e2d3fde32b793ce"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3b9074aaa4ce4660f0ecc55f8936f7de692c524"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "b8bce2e04835a53e35697f1f599a07f1091b3ef99f093e5287d75761459a029e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "967a0576a18b4fd832d6972f248243323948aa5d"
os = "windows"

    [[GMP.download]]
    sha256 = "8ae5cad5680f5d534f1e096d16253afe6ddf21bf6dbfb4084d7b70b0feb6ef5a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50988fc5939cfe32058d86efd7feebb8a2a5e21c"
os = "windows"

    [[GMP.download]]
    sha256 = "b8c5cbca682c15d238dcd7620e1c4728a582b568ceb3247c62646c73474dbc33"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a830075f2db60dfdfbde15c9051897adedbc74a8"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "e890aac9b2b020e66c8750bd12eed9a9f0e7df809fc7e59d596e4e87d3973db7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db5f37c56afb27b13143bdd02e4578e69c54566c"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "7e307bb63a2f02f7fa3c515ec057a1a115918a4dea4c87a9d77a1fc2999f8d26"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b24f46073cb67d462d438b662d07b8ecefdacece"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8b9714cc3ea9e4a52b97df20d004eeccd32206d4c650c5b9fe6e4fbd06421e21"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.riscv64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "463ac688b2ecb9970518d43f3a14b6ae7ee57313"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "23911a106452ee5c229b7816ea7d8fec45799d0046d596b3c9b46d8091a77632"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.riscv64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "2ab26fa46c361876832f1a6e901a4e59f2748159"
os = "macos"

    [[GMP.download]]
    sha256 = "7bf57d4b850f392b10e37023591a62fa963633d90c0930464dcba0089a2110fd"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de6120e75cefaa28eed790cefd9ccd056d550d12"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "45134c7cb0dcb71e7563cf1f26dcd419c8512f988522f99ad65be492dae48f0e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d0044d0922d2f761179ac3cc47eaea74968d4c8"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "cf5ace71da8b7d3754778195ec31f4f2f664f9ed65611b6ab2445e379d0b7d72"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2bb2c6129c7a50b1fc19dacd3d03542745aca5f"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[GMP.download]]
    sha256 = "f91c6b2e16ad380f9926be658fbe77ff65a7e1cb176b6992c0b155c91c0c3702"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.x86_64-linux-gnu-cxx11-sanitize+memory.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af04c6c15f5e21fcc6b403cb6c7f98253e0b92cd"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "bb12112aba8b0136ef334bfc3fd7dc23abad1529719ba502e8d01aca89c8c2c2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9bf7ff7d26b7c58a61d24483cfbc44427bacae1"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "e3fe6ee4c650bfbd10276792be32dce25da07e16038aaf7fbce978598cc9302c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "3da7eb621907f918f747ba1f7b8067535668d0a3"
os = "freebsd"

    [[GMP.download]]
    sha256 = "e63ea18c506a92f987b7352e0895552a9cc7e5dc5118ddf4d483cae313d0f1de"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f799d4349673e972d44de8429953a1cc99fa83b4"
os = "windows"

    [[GMP.download]]
    sha256 = "fee21c597ae456c7a1a13e299fe33bf85f4559ed84236827e2f619cce4ea515a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a0fd8653bf3f65552a1e0e0587d532e008179b4"
os = "windows"

    [[GMP.download]]
    sha256 = "5206e1a900bf116640b2430c6d3290027193c8813506a5e6d0be1b199bce4599"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+2/GMP.v6.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
