[[GMP]]
arch = "aarch64"
git-tree-sha1 = "df393250998262fda2c05fa5fcae1698d27d4e95"
os = "macos"

    [[GMP.download]]
    sha256 = "dcbb7413b7e722ad87ce70bcba7ceaa7280b35f7833df280145e500c1a4cc578"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa691da9ff1c454e3a6de3255912a92bdb22af7d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8f1da703cb6ce9a0ecc1fe77e51131f745ba54e934d47a39487d5a11a4a5dca5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7227a9fcde544dea16a6354c1b53a33ba1157a68"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a24052dedbd9e81df89c50aa0c6b5b6a485029f9b993da97a8635f3b6c77193c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "912df7f5133b246a9e1913a203f98ae1e59cc6b2"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "1edc9f89b9c984fcafdadf6554b481b2bae932a5d52fe5784a52370d12aa81f2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5a0519e099febbf50be3571e00dd2932794d20b"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "690c769030916312b859af13e933215fe4c1e4e457b72b80922094a3b2d38bbe"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "2b63ed86d65cf766746fc6778c349119555b99cb"
os = "freebsd"

    [[GMP.download]]
    sha256 = "21714b58d5374249f4e5d65e5bda9cdbbd36050d7a5e1385bbda417d2182b908"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.aarch64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9542865b5e2dae27837341bb847b917acf1a88b4"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8616c00775cccd0d9de6408ae08425dd22d90f30e878c285953c21ee377a3fc9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58c7702028bdfac6c940206e96a03565ad09b4f2"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "52fda7152dea4a88a1bf0d727d267010675d937d0541b33e4fe7449db611dc12"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09434da8a7cb808e2b0f8512aa86cf6f4dd0ef21"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "daa458212c26196908633c87c92200220f5b711bad9f84d17c26479c10ae9a18"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3784779d3566538bc83a7266ed188472989816c7"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "669b62d0a56608c28d9157c4241decf2f64f3bc52d0c0eb665b2ba4ee82ea8b1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6ace36fc19de14cf1f47a8df185a3efcb75288d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "74b5445174d57d754497dbd26f61c44f1efede822e4cd2b9fb8dd67cb2945ab4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1aa0b2a9c8ab86a2dbda9e4585f9ca7a7d5780b9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c26873cc94a8469ce7bec5bec1b868b118e131fc274d80e4c2451a455f809044"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f77555c874e9fb88f42a0265819b86460f44d446"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "90c13102f48986a85470a8689f177817df822048c003785b63b786ff602d5aae"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be93a2208b65112bc477d6bd8f8425ffe122c760"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "6147a6157dcfd15ca56fd1cbabb34a3f367f1f0183f9633c6e074275b7979a7b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2658ea2ca46c5692254c93ee6ca34a3063a8d2b8"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "eb9d33161c082f2d5862b4dbdf95bc84563fcca3df06682b69b3a2e6a223ebe0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5194c3fada179519a11e59c14e4789be1039308"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "03cca6bc479eb1f92f7a7193c3e907fcac9e891e6a5ab6585c6e97a173dd5aaf"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f45adf7af55bfb21ac7b4b0109bce674a11180e"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "c5b6913f08f99a0cad1f925fc2bd5e1c5371e49d9abdeef8c4e967f0117d92d1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77c1014ca9d6e28df52e18becc4278cbeb485f77"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "3776afe4234d432b648d37df5a04140156fbb6c7501d37edde667956c03c4cd5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21761320d27eade74bd2fdd6497e511e7e68b032"
os = "windows"

    [[GMP.download]]
    sha256 = "00e7b555734b253c54255ed7f214543f6cfd68a6cefedc328931c19186d65df6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f381a6cbb33b8c5d4069fb7d3e59fb1e727cc7f"
os = "windows"

    [[GMP.download]]
    sha256 = "0ad3925ae7f6c51b75e167b664863b905855283e82e42f958cc135140dbca39e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f1ae586fbf38796d494ccb3238b35d3af1cb1d3"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "493e23e5a8f8e81ba78549c11661977deca956375665be7316ebc15cdafe3c5b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78c30ae902b7c5740cb49755fb6ece5073eaa5f1"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "318acfec716ad52425dc1fb596b416e851966e2f5d1997a4b4f8c6bf6e4141e4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c82db82dbf697cfff6e4e2dc0903d495dcdb6afc"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "51400b0539831820ede288c13cb322073504c53bea5a3bcce80aaa22e43970c8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.riscv64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d074df408e4aecda01c854ff9e4cc4ccf44d0562"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "1d7c69b2ba411513dfd85b27cb45dd9a1b223616de2151ba8d45afabcd3b5734"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.riscv64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "5a09093916b83e4a64943f051c5693143d07e5ff"
os = "macos"

    [[GMP.download]]
    sha256 = "4ffcaffd1931f4b59ba421a27166cd95669bb1b60538f2dc4677a9125a93c4cf"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8af5d6d48437e22edffda70bfa98fe68e01d812c"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fd5aeea8e06730a70265e2c1b33b4a502c1b182dfde2e61a940f5c57d2d4d672"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28ecb3067c378a151332eeae1a2865736321942c"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "6a2a7401bef8976f58e0f2438a60e6d64fc726bb3e0504a0cfd9b3b9a7bf5b21"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3096a9453a51f45a79a7c877a160904f2de2d325"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[GMP.download]]
    sha256 = "d8854ca21757a92dd8599fce8012180d5996340a425bd1a7a92aee9c9c6c7ada"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.x86_64-linux-gnu-cxx11-sanitize+memory.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "097ada4563a330c5af215dabc8f30f61705e4a9e"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "53221abcd790fc143c11a08fde6ef49e45c21205d8bd60415d79f016539a5e1f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3badd38dd7d81f288d35629d0ee0f024e454c889"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "469c7f529a4543feb31b142888bacf9e9a591cd4ba7f97f5cb06e9e7c2cc5292"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "2c79b7c62d7e0c45593ca0d9da58a6cb5b0ee186"
os = "freebsd"

    [[GMP.download]]
    sha256 = "df2e01df7078bebf492d74bbec5f2ec0214a1cddb7055440c6d0f6221b045e55"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "811a9d8085fac53af81260198e477105838a6c03"
os = "windows"

    [[GMP.download]]
    sha256 = "8a141d6618e579cbcfd9e88a898da65575f0ca58a8946b78ca7f848b22737f19"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee194d3e9c30741b660d6c8575914c6db812d9da"
os = "windows"

    [[GMP.download]]
    sha256 = "a199ee4b31a180b1ee362c78d194861d1759d3795fa5728a99242f5cd662ecd2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+8/GMP.v6.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
