[[GMP]]
arch = "aarch64"
git-tree-sha1 = "06905f62c3769e57a8c8f36dbeb5af7c6f0b4e63"
os = "macos"

    [[GMP.download]]
    sha256 = "3661511db905c7a5aaf94fdbe2ed6471cd5384bdcfcf96b0035017612edee015"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9171bf13a61c79a7a98c37cfa096001e3e89e294"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "bb7ac959e10da22e9073ccfc4941cb67c24f02ee07040b340c8b2b5a8a70c30f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8771044235668b74893f3a2f1e0b057088a6b023"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ab213ac81ef82651d8e556a0fca0033d35e359f8df79c9b8f5e2f57ae7313e26"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "742c6154cf05b75084dde6501a571c7126b0b3ec"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "bc347eb3ecf5c4285a3273b43eab4299052428b9e139e676486fddf53db3c97d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce89ebe9eaf624f1bd33357fcc0391d10506d0fa"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "db922bc1512b394baeaca51ced24a4eac850813278391418c1a1a977bc09e401"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca19e5ba5ad754f30c9ebc9c36d68bc3ee29a35b"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "f535d657ba704d253fbaf3afaca7ee96704d7183d9d731e013d985a49ba3348c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ee0bfc6f624f229663c5d58a4fcf21f4b858fb0"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "3844168961b134581adeec38c072c56d5d53c68b2b207400056769ed14234d59"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3de149964352ddcfec3078837c48c6b57a1861c9"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "db8cc90dd604662e02dd33f351b5274add98681d4496d99a1922273ca0bf4b4d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5a785995ab17cdead4a3ef9169c4242aac0054f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "05c64dc70d173c81edc1253a4b6ec50d2862f717055ed3b2203ce239baa53cf2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14c8cd09ee1177a7bdb081801bbc4916309fa2d9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8d99bd8a1f41c3682d50ee686a77fb900a55d9f9d24b332fe442ff8c8228f790"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4951818f024395d433b4629e7b7df73882ad8816"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fe077a333d5053942d8b2e042cf7f5322afde35e8434dc9d85704f8864b21a0e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d10b870240a0e40c3c7984a4babbfd7abc1457f5"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "433bd692cedca232182f042c901b80d279d87ad000d1a2bba0f4b60baf25776a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd82545cee6a9695f491c5d8f7f92f647349aa87"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "15eaa53cccde54474c027219af53e44acb9163f2231698ed536d6b36ec9d4e25"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dfbcf4f566c903a16285140c398694681ff31c8"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "6a21ce4687d08e124ea6442374a319c9a7ce1c87dac9bcfd697dafd9ffb8b7d2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "250fd9282947d201b1f2de2f944d0b6998c4e2aa"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fb87ac9dc18d0f7831329c602d89a444e1ad310427c73677f664775e11930ce4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2171b526a6422837e3bdd1476e2d48c1652202d1"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "78141646ff2336cb33727737d1c008440f7faa8ba2e711ac8d73119e0a7e185b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08beadf3672ecc093e70b2ca43dc8d7cdae04e76"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "824b09bd254379f86de57b0a6a7e93c17897970ed6896a00efd96f854310abba"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ab19343632c03ceea1d86818f5696acaaeae7e0"
os = "windows"

    [[GMP.download]]
    sha256 = "0871fe79cf9c6bb62e7dd53cf4f5728013d227ca57842a2ce95bceb43f5b6bf3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74def42bcd5dd12d3a137ff0f1b82b5a13730e21"
os = "windows"

    [[GMP.download]]
    sha256 = "a39866a085fb8840cddc9bca54474de9f7f7d07e1689d34716ad209dfcaefd74"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db35e55357262182c1593cbacae377b4d8f37779"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ba2036aeb3c700c76da7e09bfc2d98c5f0cf6532964c580dd2d1f91cdf9015a9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d3f3e62e0adcec14bf0432641c8dfe58215fb3f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b82f96186275b7815357afc424b6ff6f0074a74a0c036baae2f13c65f7606853"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "deb3f969d2e63798a5ffbc3096e0bef411da1280"
os = "macos"

    [[GMP.download]]
    sha256 = "ca61a15c206f89a9ed10366c25e2435ccf87c7cd5c4a93d2dc01f000c62453d6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26376a7cef1da60f8ebd398e367711d5457a3226"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "bf6d9da6efed509af9659ea850327cb6e1bab759eab6680a67b9907de557494f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ede8a46fedee29c6ece4176a1f97baed3ff9955"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "7bb733e8689cf640a9ecb01fa7e99f1cace372f7db1ee969cc61c06b3dc5b832"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "408f836f353a50c5df95636dcb2126eb999d27f4"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[GMP.download]]
    sha256 = "4570361a75fb09f93f30f331cf429eaff5aa2d59b19092018fc4b4a0168dd709"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.x86_64-linux-gnu-cxx11-sanitize+memory.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6d2867d4259d9e2c6f8acf04bc6e1fbc7015850"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "1030d383bb1cc08344bd5085bb45c3855fafb0bbf19da9f3c21db808707ae93e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66a858b23956fdb907e91f556d813b0ebaa5f6b8"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "2d6b2f3a11bdae3d8979bafc82d6a2ceab25e815cebd2327372bcaf6f2dfbb28"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "b005a32addc44ac487fa60256cedd8a6b3b1828c"
os = "freebsd"

    [[GMP.download]]
    sha256 = "492dd769e6cea6a748daf5e57cbd28676ad92936ae48b25a3b09cf01d0bef0ac"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6941afdeac944140cf6922c9545bc284fb02e9c"
os = "windows"

    [[GMP.download]]
    sha256 = "6aa243bbc9fb78a19746251824fe072680e056941d181c9ed09b4996f845f521"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37ff617b5a6318d364305fed70d419360debbf2b"
os = "windows"

    [[GMP.download]]
    sha256 = "ef23d72398f57221cb78ef924b8dc4fe0136e12fe09ac3a490dbd0b1a1cb9948"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+0/GMP.v6.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
