[[GMP]]
arch = "x86_64"
git-tree-sha1 = "4d6e880584357be3f9924b2f996c8a1c7df7b861"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "f04f66aeefa43369e93c7228298d0c28d9550b7a0833922b158bc0dad06dee5a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "1e84f241682d19c94146e4f1484e8c383d59a444"
os = "macos"

    [[GMP.download]]
    sha256 = "597e7922d005c170c98c10d6b2f1fe1e7ec2f3f6a174a0ae7098575dc9c9c131"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "097005f0588b9fb254833ac4aac2fdf65e795905"
os = "windows"

    [[GMP.download]]
    sha256 = "83ae543d9e8c176e661afeeb387a961d6ac4ed8306aec49fd24778872ad6ad8e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "89d5b9ff1f108025cefed0ebc5fd37c56fad9a92"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "7eeb03816650e089998bab667236544dbb2862143e7de11ef3d179ac4a1f6bf5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "fd4a02fffb551dacfbcdaa912a68675ef4ae94a3"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d3bff550f6c9c9c66a24d20f9a8d075cd3ba8812c4b57f0720b1c6c722313e2a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "ed278299a0169a956d1b01012d6f0bc6f8380c25"
os = "windows"

    [[GMP.download]]
    sha256 = "ce7deebc7614f76c7ca69e14408e7714e6ac217daffae5da16a52551b605e08a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "7520730d0f945205d195e4490ff22c2b172b191e"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "9772ab6d694ace80b793965ffdbf42a8dc364f1ff2babf954acad629bb9f8811"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "6a8b4ea5ced71d50d770e41cc4867e2d618afe93"
os = "freebsd"

    [[GMP.download]]
    sha256 = "553e1c4eccbef17b64d163e8e044015aaafbfbba5fd5a39aaa4742bea0319929"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "185eea2b200bfe4afd1bdadfc87207c7585a0c62"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "f82e41bfd5d2be5ab5d553ca041b9ce9a5c325d81786f8a359294209496619eb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "fa8d05de2dcbb7046f9c19d9fb560d0b743c6f4a"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "275000f5e0e2eb1468901595207cd2476c201b160d977295ec9fe7ec900c80a4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "2eddb1ebdb171537896c5a77bfe410f31d7a5d8a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b3dfa36b0a94ebf7299f0a491b8a62027f2d1d1796e9c86eae8e466f218a1277"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "3d76de69fba42066ceb4072603eecbaa673b3921"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "83f23bceac99b01e28c907b008dba815e6bf157f5d771fac451132b92313ae61"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "7957b8799cc830d9a4baf3fd74b9700da7e2a076"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a15c25be8daa93367cb7317842bba72a13ff00e7365cb60e7835065829a026c4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
