[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ab90f698126d1e8de19c6ab062d2cf65dcf908e"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "14c421bc4a8a429fadcd42b5206bbfb53bb709f6f95d9af4bf18a6fa58c4cd67"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05c15820d550ec4d34c1037410f9bb9089d8b7f3"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "bd54dffd382b6a973a3ff3351a2360419efda4d0aed1895b10485b68cc04d2f5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5980f904953058acab78690491c3ff653db646ee"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "924ce570a667e554be131b6f016e7be4a4d9bcb3805674f284dac732be59c664"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8cb4088f45911f15f7658f4abd49fd8fc7572cd"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "1d027c2279bc7fb965d29936b4fdd94aec6fce73fa078512eb66b112b007a7ed"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7eaadbf7e35c64d0a7459c999e89a5ecd945fdb5"
os = "macos"

    [[GMP.download]]
    sha256 = "4a7ea5d8efe6909bddb5a82fe497e680c15e2b1c847a06a13fc64597bec32ac5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c38fb4f27f0a4581303e4acf08d2d4712faa4eb"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "39342be3866d7171b64ab492499a10030071965549d5d409d8867d06bbac105b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72dbbe550e5ee2bee3e17f4f8a30ac392acee5d1"
os = "windows"

    [[GMP.download]]
    sha256 = "362a38432bfeeda17d1b02bbc83e5f83ef8276ae4dc732b0fc7237966bf58e4e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b63dbb4cc40374515b20b0a9d97f4f51efcc72d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "130bf229c56f25e396366553752f6215be5491520556b3fda8ed79f76af4eca7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "103a9b9e13504d24cd5cdd12e530d1d6a1eb7a59"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "0bb07a22a7cd5dc1028db8b1dc6bfc897bc8bad67d42ea644d58b63c67ac87d8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9c6cc64a58cb396c3693ece73fcb12994b56488"
os = "macos"

    [[GMP.download]]
    sha256 = "8693d06c3ad2d1442722a85519d754619f4ed998b9189f13659e20db2a2a6681"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91d915220854ff4f1e21cb250a955131eebadd40"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c65ef226121b2f83dff5e0706f9c2a9c89d631a9e696ec4245db8f34d523a1b4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbb46ccba6f0c02c102bfc80ac5d7bd38b633192"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c8dd7e07cb82260ef34682e08ef6d2924a610569e2f5cd98419bb2dcb6e60524"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d21bb6a0ab65a8f66648e0463330a93664893ad"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ab29a335c8341add421739ee0fbe989b49e5e8b2fd9995904689eeee6bdb5534"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30521806c3b85da69508691b0107b0518a63f8d8"
os = "freebsd"

    [[GMP.download]]
    sha256 = "324c09761ff49f4cb523fe8ef721bbf40f601029a3b4f3df74daeecaeccf89d7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6141535a6efbc2422be965ec69b1d849e2a5f157"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "b81b8c73c6a09e6ec9365b3801a5a8694a7b8fec9dbe21575aec45bcb00ebba9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25c468b61c7d88edefa529d53dba7d9fd0dfa980"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "f06a382cf1de344e492dbcc947d32b0344cbe524f95f55de0c26fa0d69e3dd09"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b1764a16e8442a8a39ea59e0b37940ed7f605ba"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "a9b24f822050a99f20370bb66807d2e011e2d5c8f66db625f636795700b3a7e4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7eb6db3a205a1baf5b55f5b725a230cdaab95f8f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c803fa0fa7152091df080c25569fd35e724d33a5761d793e7be9134498eab1ac"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79d645e48cdb6894183eeff069c375fc46abba50"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "e39b05c2379a311a426946150e5e10baff03f1d44ae03bb359e2594d9973411e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a25ad4178b2142a5f086a691d07ac155a6ebe3b"
os = "windows"

    [[GMP.download]]
    sha256 = "2c50fc577ee090d46faba104ba3a4f328cc642024377bcfd968f48fe93954bca"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2996c0b8371aefc9fd656a87dcdd6b3f9f9caed5"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "738390b5d59be5650af95c03d82eb90193d53a2deea4f009e574e47748d80cf3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0485f23c43927ecd96177ff40708f1df2ac25109"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "e9e507486448a730e0a87c7229bf360b46254893cadc67da5c7d2306437c0e1e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4648ebdbb2e5b1fa2be42e3581fc71d43773a66b"
os = "freebsd"

    [[GMP.download]]
    sha256 = "bdeeb7504760c248aa8121acc433d8104381d618f5144c21e56bd8ebb4167051"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b13cf0e2f70ddd7efb0ed803e0d810707628e60"
os = "windows"

    [[GMP.download]]
    sha256 = "bfa320b37a0c5597809792b33e472ae573c3ae3b9823dcb51bc93f4594f24c59"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "588f5c17cf408dc9a4ac0f26e445b51d26f584e1"
os = "windows"

    [[GMP.download]]
    sha256 = "c02853d8e5cf0c89611030d28ff930c2ca3ff412440a4da74ff49ff9511f8f7c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "300bc3342f55310031847d92010217dbf82fb2b1"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "4e4694472e941f3f16632bdf532d953948a1d86845867bca324b424a444470d7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+5/GMP.v6.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
