[[GMP]]
arch = "x86_64"
git-tree-sha1 = "bb51389ae77e9d20b7ae25641517af2cbb51f59c"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "7f4893b5ad980aca5034f598453cb9b124daddc6bc99b1f40e48da60a25312fb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "2750c5512291d7a14a384546760eff0c671a13d6"
os = "macos"

    [[GMP.download]]
    sha256 = "2e7c93b2956ceb76e0c719741e1ca7cb6d940c9863f947b0747fc86f7c351ec5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "267d0a303fd89e93153999dd4a58cfa7738d85bd"
os = "windows"

    [[GMP.download]]
    sha256 = "5d1e711b45986662faf63d9dfc6952eccae9e88474a2691c5a5c0ed9936f2449"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "360cfca45edf72697c4e32d22afb62b24a22e763"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "97d5b26e9127596a222f653213bc1ff6b192c016d185b99160abe2327f0b4bbb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "03de7032c779b4fcd78478037e1dbe2afc20ba7f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "e0f5f22098b61915b4f234ce4241c891882d035b4d51ecb8c93f10d6a3ad81d9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "0df94489890c1f4350e01b3d57d649e5a459de95"
os = "windows"

    [[GMP.download]]
    sha256 = "a487593209f8d5931b696dd7908fd7cf31b5e66dc1aee47872955ec9d33aef3e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "0a5365013dfeadc9d5795aa1a223c59ec3386eed"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "12dc1cdbdd70d5383ebbd476909be5e60dd73356f27312ac19060f4123c77f71"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "3aa6eaabb6f012d1bc5e379b3a03db60e50f6ebc"
os = "freebsd"

    [[GMP.download]]
    sha256 = "909e741805575e0cf41508d23995e961663e666e3291ac3b17d63539a24be634"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "14497dafe41727ede8aeef2a9476a7c96b406678"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ba3ab27c5216603019cdf95d74aa2e926d7d4240153706cba5e2bb4b5643b940"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "9f74899d5388b4e8ed3fd41659f9cf215a973b85"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "7d4602fadf9869e08cb26b31235a65f07376006eff954ff5d89a9350600e805f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "9c3c8fb3cc48df2141cd77a5ec3ca80f7e194de9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "34b82bb743b3987e1d24a766a1188e59e36b6c052bcf6b262fdfd70ce20be8e5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "c07c4c526bb323cf25945c21ee83e9fe486f233a"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d6ece42d7d593371bb7edbc8bf3b09be3c0b52b9728d6f6bdce75666d5bc1bba"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "e786db977e765d1fdbfe71e47f14db0585137e0e"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "6655d890d5b211c029fb3f7e0f7f7bbf7d08acddcf408ef84e51ed1480e3a4eb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
