[[GMP]]
arch = "aarch64"
git-tree-sha1 = "bcae6f918608a5e5003f20aba25d267d7db5e50a"
os = "macos"

    [[GMP.download]]
    sha256 = "c4bfcdc6f8c787ed72c2f892a8d2cec52150db2ebd137a6a056e9d6aa588286e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31e7e1cb19656afb8318c4f619ae913a489ce651"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "4f4e4b75199bdd51c640338b57260ec4de0209ece761738c4e70e0a73365b073"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ef7ca4993d9b588b813bbdbe88d5707c5b47a51"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ca1ca35bf9fb9f0c4151a76932252830acfa2425b2e9b554776e1389cd7c8205"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d2782f7f1a02dcff2a5c2badefdf3316089cfa3"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d2f55477ec9749e54390b8a99c67bec4b1d5c87da48b5305012d5f70f06939c7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5661fb3dd4d4d4251138454594b9c45944f8622"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "c1a88e1815b34142a62f5e16d30454bc600526e0dbb90e9612390fa7c3830d5c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae37d3b80ffa378373b8b8d9195e238cce8abc69"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "68109f87db3220cb986dbfb80980049c3474a86309bef4ff77cf8e5858aec9fd"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a5b376ed851db615de17b88fd5ff0b44033e479"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "941bf60efad2c533b0be21f33e71330f11f3d5e72f01eeef89aad5e4a14b03f4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bbd1c630880ee93966c97b3cf2f98985935998b1"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "f1e5e0059d93dbe3aa5f0237744c863e1dccba646cc50500d9578308eb58f3a5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45d7869a32b21b35e65d41042d7933231e7f1927"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "a0066a29648dd85400648f46125179aa63009d8f3603d59f1ea31087908c4858"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b23c5d43edb689d84bec34659e4a83d56450d990"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "1007437225f3b2fa2bacc9d5fae94704aec62437700e8a7beb1a73d3beb85adc"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35370eb0db7c03d39dd1f24d2f20e419fbb2ff3a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "1d82e5e2099fa65135a5968dd1955af9a186c09dfa1d0131a75a4662b57f9e13"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6dc1acff87bfb1827aaa3e7e5ab90708fd5c7827"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "efbf7004a90cecc9c997fc7d4d672fc5ebe5ec61b307d284c9df4f33331f5e4d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "559eb5c168420582e1b6d01c4d962977d1cbaf11"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "7507d4ca3219a9ff8eeb700318a5a9a4fa2bfbbde0338e39b0c50e98b7ede01b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1482c631290a90f7dc866729c2de5fc3cbc4f31"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "4822cd46914b436a4b2fa0d6396ad469dd8d77cdb12112f91c6b8d6fc5308c9f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b097987c89b1895c33aa83e0acdef11611b053f2"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "aed551b92e83ec8d4a5ff52f71590e60bc2633eb72b991a80e0e137b843ecd68"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68113e6a80ac742d4f577113dac4a62d871826fe"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "f5d99e713788721bc2f52d717fd74b31d8a38f93ddfb9c8c56c3d2f80ac30bdb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef1b092c13b5573a6f8a076a24b5038768de3e49"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "da509adaddf822b12a22a9e27d21fcea7087f5b1d8b62ba1f0a9d1ec81c06bf4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cf545cd93c6e4bbd6d914d408ec14577caff4f9"
os = "windows"

    [[GMP.download]]
    sha256 = "aa8784ded3a750ae0363b8090361d635f55c19d5a9b367c15deabbaa5eb0519b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69143b5d25a3a27de530ee7bdb55ebbabeaa5833"
os = "windows"

    [[GMP.download]]
    sha256 = "3e17e4951f8dfdf94530e906d459a5f9172c0214a4beeee18c1e238180acb8a2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1fe2e8dc561da19b7cde71dc2a9cca4d1c623c80"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "74b4b5067f0af73a55b54d3a92c0e04b535a5751a4b7cc25b740f9dcdf7c1178"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b0be0af5e5c6c7d2f50444fd927b4e08295db82"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "bd56b5f5f4ac3660eeda502a5d52691ca16bf94e515656c4751a58883a6ecb4d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "4963e79493c4861f577fe7cc50f940bf7c15d1a7"
os = "macos"

    [[GMP.download]]
    sha256 = "c1f161efc53001915b76e5c8fd07c59965deb0a07fc5b32d21cceb8c0eb6cef5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab418c03ea1707c3e060edb145223d80eb36c516"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b17473bef449601599b03a107c365d528c27ba5244adf0ca3e2de97204523ff7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5db098bdd59bf92d12b5c058a2100ec26b385d0"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b865349627b533568346fcf2ad35dff483579ffa39f4f590d2b98613378da008"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04131fe15e0901d7168668fa8c3fce6c1a66fc73"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "e2d09158f1988d82be8c6969e1f31b9fff0abd4b38685d612e56ff174f046eb8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "637fc93bc883d5a874bade935fe70e92fec45dfd"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "5e8b861e4329a6fc588ae9484ad754661505f4098ad2581573dd78c41ce42172"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "4d2f2923e538dc4da34c013aa696b918ed34c838"
os = "freebsd"

    [[GMP.download]]
    sha256 = "43f2d2c1c46bf53e2ac29fc02651ec636e19fd920ab3c775d55987a78da825a8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46cf670ddf3eac4cf1eb78d9f4420c0d062aa5ac"
os = "windows"

    [[GMP.download]]
    sha256 = "00c2a48772c8afc1a2b8f110423fa5204c6793e78be04053e6ac9bcbe53a5210"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09e7c52a9886438bc4412cadaca58ebbaca1cbdd"
os = "windows"

    [[GMP.download]]
    sha256 = "fcb45bf96f2a677d981af8ce50d83c55345cb6288e2367f49bcbb0cccab38fe5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+1/GMP.v6.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
