[[GMP]]
arch = "aarch64"
git-tree-sha1 = "8d3493b62ee79ad957d35a707d772b2f7104500b"
os = "macos"

    [[GMP.download]]
    sha256 = "5ddd46f184bd6562da3fedcee856a74a548bd12ec9356750519d711f17bc807a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66ded0186426922fc54f4af8afcd5d65d709364f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "dc0c61103956556e1adfc5c0ccf3c3bdc8b21def0328427059e1823232b8e236"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91309be91eeb04513cd2048a0d14303792f75153"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d3bd99e258b59de3194c2f33881e8fa56c97e7ce6aea10fda7ce62547f02795b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "420c5af7e3a8f6b749f394e340bc26f8ffbf6e8c"
os = "freebsd"

    [[GMP.download]]
    sha256 = "ed795d20333fb6eb4059802edbaa36c4729af3913e3ba8be83d04e6e9d6107bf"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.aarch64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c8a931e2cd54f96a3ce252255661eadc83ca75a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "864a89e7cb7f71683810aae5e2d7bd633ad6c7492959a31a13e4869be1b4b512"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c1267f20d68d698923f82fbc8a64e62cf29012e"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "53f332b385b39c21c03e7e736750fbc6382fed1f64de5ca638ea20f7e06bbd61"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f104a6f7f53b4b2c9d5500e8f244668b117fa29f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fe1976cd3eb9c713d6ecfecf22f4d2fa8951e32d9d666ea0f7c2007a20eec8b2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "662dcf4ac506ae3109344ae03b60f118e4b5ca75"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "11cf7751af7aff249d855633475e2abb543089e37d697bd634943df56dd296b0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1911e4b96dd4e8371af57e8b3ebb32459c5312ab"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "5628a974b94ff7f1798a4916fc59a66d4efa37c8e1288b0e69eb84913c62ff72"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5afc26d3985d54bbb3051a712cd57571fc3ee5ec"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "9c701f4bca72429f0d466ce28b444391ed2555fdd3dd51623a773ef03e574ea9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d301c5edd57dace1fb49fd5889289e220ab4c022"
os = "windows"

    [[GMP.download]]
    sha256 = "64daf48f669a091e89069a2f09828d6436a59f72d21bbf2a5c07df706508349d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0cd3dfa0db2af614997528a5cc68a3f92918cb3"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "9aa5b998e3169f44f81185b02bb5881d4e6989c70544d05361438d64ccf2cb96"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efb885a574656ffcb699c47b4858c71c8f021d83"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "1eed03041e713b5820fcab7c0c750560ba1b8937680929ae87ef293a2fd8002d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.riscv64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "9472764c1144a7bae7455655e338418fc3cddc0a"
os = "macos"

    [[GMP.download]]
    sha256 = "b17bc7f15fd7660c9c2cb59ac08feeb85090a739cb760b56f713b3834ade3582"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a030afba7c0caed5c163ec74e3ecb97b13da102b"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "4706f2f7a5cd06e7cf925abf3c1918f5542a7cd4cbde20bf0e0804c5adb42b3f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e2bd9b3b0ee86c08a7d62c3bdd9dc08cdbdc722"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[GMP.download]]
    sha256 = "e14d7ed729781cbdbd575d7b89f9183a97ab7744b7043956339d396ad3d2b016"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.x86_64-linux-gnu-cxx11-sanitize+memory.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2c3b5fd172d50850cb3f528ac03c5d239a894b9"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d54c4dfd2fc0934b087b3904cfafd76d8be0ccdac6ff57435e5157be3ae09a62"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "2aa9277629e61d1e5170b8d27759a10189b67886"
os = "freebsd"

    [[GMP.download]]
    sha256 = "6440b169ccbcb883069aedd0e1a5bf101d8c84291f49f41d16f503a54653b087"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40922d92a6db35b517e1207256a6ace11aa7c016"
os = "windows"

    [[GMP.download]]
    sha256 = "2db8bd83759ae387e8975fe3479722a52a5c9bf3920f9548e7f469c679f5da56"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.3.0+4/GMP.v6.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
