[[GMP]]
arch = "aarch64"
git-tree-sha1 = "9af15e764bb15cc93e3adec58cba80996a907c4d"
os = "macos"

    [[GMP.download]]
    sha256 = "fdd315462d05f0749a57843cc83db318aa3075e1d1b46556ef6afd420e469f87"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48d34ebd0c08fd8c186d1886b8f75047d81b095a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fbc7523489067cf374be199027d57131a544546dc6e21524e77481aaff5e1fee"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49ac02e98e0f3303cdb37e45c77cf945a04e36ca"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ca293890c4e95759f3c756767f5520f986415ef1ef6b8ef29968f4d62fa45744"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ee7b054eb3ae6e3b5ccf6091c91030b55a71706"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "1b090082c9e7e9def28b4c63e42140af8e48aa41c3d5dfa4d6b165278642e811"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4bdbede4501b74deb3c1c478ec450762c43b987"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "cd017256f573b3eb01bf248a4c8c46e9bc5e92b0aa0972e903e6e7aa9099b5ab"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "7e52b23e2f1dcc9398dbb46413a2f0ee254be105"
os = "freebsd"

    [[GMP.download]]
    sha256 = "e34d03d3afc4d067b5641d93da0ea3e73263c2b9e2a16d5d01958359e1ca3458"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.aarch64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cb6c23c96d785eb1aa2a457ec64534117a2b749"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "351307b1f6e00dd956a8d710a134d9764cf8e5fdcbdc579adc61c0387dfb845d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a62e3847d4d1697491916f9b34633be317151571"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "2a5f88a4707a2726b5d1c3bc312f03af75831e44c8d2cfa64b942cc6d8e5e28b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5532c10da9852f7f0fb4027e8d7d9d06ba25d9ab"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ccc60c8fa5c3b4a84905e1956e9c56f01892b2cb20b1bf0d015fedd68f402df6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f1037a46a352b0dc3456af037e1a9cf247c345c"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d474d1b526ae6520cc3588c38409604140f21407ff4eb331afe6c39cecb80926"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e757ef0b92082b29601ae5671868465420cf88a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "7630d220bfc60426e6f555f841dae3d3bb4100fdc345f4dccb067828d8c81d3e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4c2ff2bdb9605fcbf9eab001af2fab44601e3ae"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "cf6d067d3b5a7bcf6f0e5e4eefdafc0ba06603a93b668b6823e8a2961c23241c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "974c7a9a7aba50e159c8a83dd68b28f38f055834"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "c936c0b3aeed07b019324222e59b6ec5a3a7c8b1fe3f6a6869614a83f0c77d27"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efb564da251baf859a13fc2ab4374ef7e440aee1"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "e00540f43c103ecae1a4f61809659786105a21172086b8206f6a823eedd22d90"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e559a67f4ea448c348ca155ca19d619bf789b56b"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "68c6f4a476d0e8ca126919296efb7db1c3eb6e0f3dd5d25e0575285b5a9dbd20"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbfb79d0b55064bd07332b8d2b13a67049e30b63"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b247f20bb4671159b234bf3170071953f6e412489c99b48f599bc3d99ca46aa5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6caac255bd05c25a3a140797be22794dd92e3458"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "59f8551c40f8b4b7b7296a6f874d2dc5704115aaf68d092cd0d4109e0c6d9c35"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20c3588d598834178218244471d7d93853bc2b39"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ae03b5c41a0d168fd3b90fc0cdb4a79ae716589cfcdeb00950420819723de5f9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb03926f118d1b7cc2fc91f81daec0bba7498ffd"
os = "windows"

    [[GMP.download]]
    sha256 = "8a4cb51519c3cca8ba0ccb6cc8ba88f0a2fd909c62ab771b5642f9c84f14841a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d188b99cefee2c2102c8eaf734d3750a02ba0e8d"
os = "windows"

    [[GMP.download]]
    sha256 = "dc5bd415c1615280c10b7eacb3834d4c34994d813c40f7df0eb388525b96b024"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aaf9df64d3e6745aa6922f316bff7ae82ff77607"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "964479226c55574d010fbf655d44ceceee56102f3d60a05a532c937cdebf205f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c240499186386081b51c543d7abae07ad116e30"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "e0e9378d3f4325b93602811ca66e546c7aac42a1a1e4ad3ac72c9d4bb86246b7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "77cf8478baa16de94f45c97565efc79335935796"
os = "macos"

    [[GMP.download]]
    sha256 = "8d840b4d24afd6fca6c4e81562fd73a76675c1740581139ad896293de5849156"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63778811788915ec1673a34b755eea0e6bc7ff86"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "705c53bbba58c2b38552cf9d05b80a02aef2f80f9d41d5f5bbd37308a1ab3c59"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18d576d64431c003d537010e3e8e158b89eba2f5"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a40df6af6dbc7893afadb6570f1d03c87998f29e376408b641bdefb813bde9cb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e6df9e7cc141234cab9bc074b45f679df49da45"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[GMP.download]]
    sha256 = "9cc56b3aa404c94da7d5747d86a5fc28f326f3c5ee4504e26e75d024ad164ad8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.x86_64-linux-gnu-cxx11-sanitize+memory.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82d65fb3ae24f9fa584e37ce17dfcd4115478257"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "9d15f2b1715a60fe3128cc8a383db039e394de28ad7eb953acd0be1e0a76de06"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4e53de44ab4b758150f6595666c5d56d8531dd1"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "17f5c053c6dbaa905d68d9fbcab531a4d84f5ea8594c31bc66ea22c3f5f04a0a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "8d0f065775498520f2ecbe0db12e193839e9116e"
os = "freebsd"

    [[GMP.download]]
    sha256 = "8dc5cd0925564db829f540cd2b992c55b5386df9bf20548b9413ff79884faf8b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d106817aeff9eaf18647505c0adbf31f64e72fc9"
os = "windows"

    [[GMP.download]]
    sha256 = "ec1d6145d13132ce912cc297a152cf17d6aeb590a51e93c049aeab0219979ed4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ae46b145eabb32e44ebc5386916f893a7d3fc2d"
os = "windows"

    [[GMP.download]]
    sha256 = "b28c5b844d29b58ee50cad73c2d819f099f92b4de2668b8887990862416dc9d7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.0+8/GMP.v6.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
