[[GMP]]
arch = "x86_64"
git-tree-sha1 = "8bc1938e09fe91f982959fb778085ed1b7b54074"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "a3492d40f6d95ea4298f897e4b23847f07957025e296918ee27ab8b887c8e5c4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "d7c455ef22fa29ea99e731e98ed5d8908c782ceb"
os = "macos"

    [[GMP.download]]
    sha256 = "449e36c4e4faaa1d2d525daef1c6152f766871c74538bae77d31b1f19e27a70c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "9657e63d8459de8d67d0ddefcf5eff4e87e09db5"
os = "windows"

    [[GMP.download]]
    sha256 = "b911ba232aab317bc20314a9be3e7b85621e0c7431af77e43b233c3aa5029153"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "a2bff1ce513eb06dafac86205fb8aaece3af411a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "4695e21da3a6dac28e8b945db40c135ef07e30fc27e336d3722999fbd0a93fb5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "d2413e66143e4897b250f42bf880e3bea62c21c4"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ece46f5626a9be5d44d4057c7e044ef0bc11d21c126820cf92394b3aa82a0e91"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "ee0b383f29fbcea3aeb24f9b77c29fd7cb0d41c2"
os = "windows"

    [[GMP.download]]
    sha256 = "fd7f2cb4761fd2e38ad757adb35c5d9b8c5f964be4158af5afd0ac01aea0b247"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "397452e4769898f10ffd6fcc38caebfc894a450d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "3d8b75886cbceba151ac4c4e40205f96b582bced47f737aa949a3eb1842c9db7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "9cc01d1b489eacdc4571cb6cc8b783dfe31d1d50"
os = "freebsd"

    [[GMP.download]]
    sha256 = "03d3b7b042ff6d45d4f846c4be33a0fbe046b6526c2e5ebd17a0edd82a8e29ec"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "2d8cdfc07b6577a6cc85129dc0af46eba2bb709d"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "fa2fa1ba91a901ca495b0fe3c02f8ee0af98b0937a9ab2562442ceff518326eb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "bd9ad0afbc77d0208a50faf2152d87846c298ff3"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "764e9bc590c0b0812b65b018b51430cd78d4b176329778cf6e952c37986a8791"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "ca1968d36bb63bc711c94f9baa1d25a196f7c612"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "54fe951eec960262a180b42abe7b601ba3dc23c30a2c5d8f9e8589b98711a1f5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "20c34ae9b5498cfc37dff6aa931523bc67cf0a65"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "a35840b9996d7e8e9cb30b5f6f6c65f39b8a03500c47bbde531160c75015493d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "77071711c7899e36a8f6de9f0cb1c54659bc8897"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "dc4c230d5f3c2262cc48d5fd1ef6371fa6d3852312ca390158f4d05d54fe5a18"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
