[[GMP]]
arch = "armv7l"
git-tree-sha1 = "517f8038695aba7aa5e64f624ff109e6969fd819"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "40392c2ed2df591df18ecb3ec4c2b17963d2613854a963848d54040cb2635fb7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "a0bc635eb2421128124cdc8c8c30880fde9e9281"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "d6aa6c376ecf42a5b7640dd09876d7db2c72969a70643c91e4dd54621cf04cf6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "189210d21e0e25f7376806513cafee84d13fd8d0"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "2a883b7b79cb8d77becb38c8aef92a40f6fda67c132d0721a8615115ed5d5e7e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "207a75ee339fc47441aa96f35e13c9bca2ab2292"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ab323b6f1780cda3ec0f2f3f382635c5675d24f4023c503a3657085fe0012c96"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "714206d214dbd73d7c30adc05d52544fdc6f7a80"
os = "macos"

    [[GMP.download]]
    sha256 = "2597b034fdcb7d7087b6d8c6b505e3319749aacd03a9bef73f14c4fc817a0390"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "e4bd84c9f4a300772fd0ae4ed448d0fddebbd7e7"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "dc99a77b1ac5137d586fcece4675c9047c1f14961dd1a94ccb11d0cc45378aa9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "cf589eda7873e2579e9ac47e8a7c3826baa94a3a"
os = "windows"

    [[GMP.download]]
    sha256 = "bd89e02a79c105df34b06eb4be30d759d92d9fd74bad061e06c1b4dfd955cd2e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "7101070a8d500fa45597604e93e46bc324c802ca"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "5afebed0e8f3814b167bca497fc64760198e6b72ce07503a256d8b3de0d93105"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "611b884f108a619fd43a1f8b880eab6e42edf9cc"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "09e0854fad4850a7314d655fb0cb575c2797013e5e2cfe42eeb3cc55446d2f60"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "2a5d875c7764e963da8785518cff2e470e0ae304"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "c528a5271b2c11161df40125552a005e8d632c4e2644678438b5fe258beaf979"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "814422a48b1945fbdd3b16991e1a016566081607"
os = "freebsd"

    [[GMP.download]]
    sha256 = "2aecb5aa2566ba025cf9911d89dcf09d88f60ff8b911dd4e51b0647ea6a4fca3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "5ed265f7b5a35bc4a11a3ed3b4afcaf8d1e6c667"
os = "windows"

    [[GMP.download]]
    sha256 = "5d4bbbb3bde9ad1cd202aefd32d7f6f4edf54ee53ee5dae0a5c2b2c927e296f3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "204c1bb4cb82d9c704c0fdf565d75fcf564e2452"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "99ae93de984ab1464dfb6f393c7d6a70b8ae5b313377aa55257bf5084824b84c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+4/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
