[[GMP]]
arch = "aarch64"
git-tree-sha1 = "331c457c2168581687cf97c293e7c724b2a5cf28"
os = "macos"

    [[GMP.download]]
    sha256 = "d29e62a4e77a25f28e0920846d01e18482610bcdfc9cd44ce014469b5371735d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7e902016cfb4cbe99cfc45d8df0de737d5027c9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "e0a2ee8659141e4b13258aaf97f43e6a9f5ee0c53f520c7d3bc2ca4b9e792e2f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "214b174c351bd5ddba4e9af0bbac1ea8b2da71df"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "cb8185e80da83f998ed756e8580f99151ff6db32d5487ec43450fec52805e1c3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "733b5a0e8e0528c68f565dcaabbb26a28192f35f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "574d709fbe5ba599ddbc53b379f786a5484897a994e82f5f91e7023c13a6becd"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "944c2c33e17acbc7afe50bb292259339a9ca87f0"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "15d547c0f1d0694efc2c3c8350df5b8d1fd5bda309b235aace0cac1f045e28bd"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af2eba304f826b1d0dbee270a661d871a746a91f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b581952fdc93e0810d9b4d333a9d165205d57c96dedb9a18d5493b6b9a4d3848"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a91d3b659acf2ca64b0bfe626c06132f0172196f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "1737b082f23b62d09099fda671db24b05108ca75ff5062ab004a957da08b66ad"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d8d8c6d5696c844be012380b30dab3a3d60f5fe"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "8266d59a3db8f14983b2c581287a9d0d42ab81086f35496dda3b16624d9a110e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a59377d7151413479f0f7542d9e57edc27fb0e9"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "125ed308e0086dc8dddcddacca73e8a02fffa5b5a2db96c86f02707fe008bf03"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc52c87c93bea81c3c0083bce8d451788ce2f95b"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "6a9bacf2195427fe32195acca6dce5a9027c6707b9420673fbfbaf3477fa8ad9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf2bb2c41c65cf99ab4642cc91cc845973073872"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "86e8d29344fb6af0aed20097b3a6b1b20de13bfedf64cd868a4d864c9ed755b0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ec381e05ceb16df5baa5dc8fe15cbe8c0bd38a8"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "76ad3d9a002546707a2bb49746c9570f2b59bc34e9df6a46c76b0c4c9ca4c538"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ac98ee8922af2e7de558e22faf84641b9b721fc"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "d4f69b0de1df103ebb9d344a64bbd441b350be623ba536182c0303ee99c30b8a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31fe24358cfbdeb2fb42383949d654f6fe41bb0e"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "9d95abf00a1226527821140d9e8489ed77610529d4b49256612109c7054f8d6a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79bebd64d8acaa7cff79b11f84fcf1ddd1185a42"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b31772bd596e52269962e7b1c6dcc7bb75442fb1f0890a0b3587fbd41acbbff9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9aabd1d83138f6072da40ab98eeae7a9bd57034f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "9150e907d5b11c9bdb104da43ed93203c9acdfd06905ece72e555577e0343cf8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51f24312c4201d2752d998e4627802dbbfc6777c"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "4b2a3437d0506e92c7d5ed1ec944f548cdc69cd37088cd142c63b6904830d0ca"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c46dac6f09e7f2e31b791c7322989a46f396388c"
os = "windows"

    [[GMP.download]]
    sha256 = "7b2da42ef3ef160f172c9955cee8d748682d9454190f77a7b2c06209d315985e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac54f5bc8cff2cbc543b386a6853aa90521a6fc2"
os = "windows"

    [[GMP.download]]
    sha256 = "3d5ab0061be315e9757d8b31c804dc25b4357b495689dd8391e582a2f045dc9e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "278601c4143f9101f2bb36116866d9d9f9c0b6a5"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fd53358f79f2620d77add12abb8f5f5d2af8f7b22314a67500bf3487eae8de8a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01711f4050e7f253c6cfbb4db1ed8ad9a59d0a70"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8ba515cbaf8e428e96897aa9fd16a3f62769ab927c9030c15be78b77ea666234"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "62ae51f092083fe75c67762bd62124f192caf190"
os = "macos"

    [[GMP.download]]
    sha256 = "c88b59526523a8f6586a61a01ef8f600c2f8f5e57894bb4b782837fbf6d18ea9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ba01136e8dbe7b19d5eddef82d9c1a58828c8f3"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "6a626ba6dcd67bb9a4c90bf00111bf8ac7076b2ac7fcfff4e5b2a1689c28304d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b7438df80a5613dd61557b7470eb148a7ce0626"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "393188ce937f0a97e0417c83a5db223a5862bfbbbffdc01fce613f76c29162af"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83d8cc761d783b9b8d5f35c2faa31a92a0bb8424"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "90599ae167a1e675ddefed1eb0e0ca62ac3197df1a7838892b42c7feff23d4b4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9228c6e17f4efd2bcae5a3c3335339281b791f8"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "75da5e67f26a377a0c5ac2e9a1ccc9a19435dd47bbfab27937963b495b91ba6b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "224e6ca87cc22e8cbf467a285cb03e754ee137e0"
os = "freebsd"

    [[GMP.download]]
    sha256 = "c60e7789eae6e6765d5e6892aae5152bff22c9da78a723e82472e1d9093c7820"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fa7531e2b059281bb182465b2a86c4bf53759bc"
os = "windows"

    [[GMP.download]]
    sha256 = "2f4c8f7b90812b6dc15034edd0dcc3bbb09363e4671c23c04e159b2d5f02bf81"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10c5fd0c2042337894129c0734f2276a9f6f3c98"
os = "windows"

    [[GMP.download]]
    sha256 = "3c1fe0f3e5320fa886993dbe15d5c9ff369fe4cd906922e981a957e9a99f2914"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+2/GMP.v6.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
