[[GMP]]
arch = "x86_64"
git-tree-sha1 = "169f63aa10060796260c5975eb9c2bb939b11734"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "3822778c94dc2f222880b621dc56e9fd26989dbb762759e1d89a49b0024219f2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "73e52e8bd0d8f060c7e7c658486b66d8e2b15048"
os = "macos"

    [[GMP.download]]
    sha256 = "d23598791d73352508a16c18b675ea6199c9afa7dadbb311a7f02c9a3c3fc9f7"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "760ece1127cbff9d0bf389b52bb57119d29c61a4"
os = "windows"

    [[GMP.download]]
    sha256 = "229d12abd6b9f3b20d31f7c5fe714552b4f4bf968cad45b6fc39fe3f9e31d52d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "cea03de7177a2f197bd46208943cc8f122c860a2"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "dd8ec4c25bbdc953fe5b37430364bf81c48b452a09a3a1340a4341c86c007b37"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "8cb9cf09f0b62784133cc04d5fcbafa52c0e3514"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "f97d1a64e3ed60b2ed8a8969e514b6b663548bd6e8c466c97f662d63429c4f76"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "bde5d89ba964c7609a7826df1a6873e31c09dc12"
os = "windows"

    [[GMP.download]]
    sha256 = "bd0265bb673514b2b3a6c23fe1946a48bc284346a433beb9fc99cf61690bdbe2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "7a388af9c65a9c96e79bfed7e670730aaaa3e692"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c46a945a9d30f195b9512e6951be5dfd7f38146df2f50e1b736959a453349d5c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "8ec68b965d40d75eb0d2b920f49bee54c70661d5"
os = "freebsd"

    [[GMP.download]]
    sha256 = "d156ee54f89840a5ccdf1a710b1ee525798c74abae41f799207375e89c5d18c5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "cd555046566601eee412f21dabb4ba18ba6b877f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "9330aa54c3f88c89479b20e69162c9cb906dd39fc56acbe6d655df29c297315b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "30b28b1128103188ac46f16f13863eefa9df8d90"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "e279a097a510746bd94297688e2243c794d2b5516c7caa5f2791f03caedd232c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "ca49a64ebb14b0a8a12d3f4d1f37f9e41d153700"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "17a2f1a9df15830a9f0ece3ef6581236231a9d0cbbcdf7918402a6dce9c19741"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "17281c819baac2e8ba0485bd4b73bedc5a9f14ea"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "74d118a5053e569e7604f8b7104fe3aa265d807a7636fa453eb905c59358046a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "a27db6f65c413421b859acd79ee7378ff29849d9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "515103858c9024118c205c85230c2d9da47c4920b54e283519dbcf8a2dad5014"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
