[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82aa2f66c5feba902c64bb3097f65612ec4d383f"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "f0693c07a3ee485baf88b2641f5a6072cde64fc509e9b273193446ed5ca112e0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e9dc78f2af92713a31ea04272916a1ef90908c7"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "1848ea280fa5e186597aa175cb1d2763482d494ad8c928f37577efefa1639050"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cac210c6eb92f79493f738068a27f054475dffb0"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "946dc06e84437ff7a396b79a7e42d9a01fd214bf215f4ab3229a8f6188f8d54d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13699ae132b8c9296fd9bc7f07d1ac7da4bc9dcd"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "a94a4592f960492af278ee8f51cbf622f6522b135b67e7b5ff5677d2360e3c66"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4326d9ae42d43f488298d2f87683c0ceeb73fb6a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ab669482fa88a00c847aba33b2db0b8c29eab08f7279a4489049ca3e97ba332d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a4e546be89530936b68b556b77d4172a3ab24fd"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "169cecb63695475944e4cc47c0dbd18bb57618374c48a530d61b62ccfffab2e9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6a0a523b4d4d36101982ca3a79e862360133ea3"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "0c4c2b7cc8d40a3b7396bfa1f622dcd0881f0319c34052cfcbaae006cdb0d87f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6eade570a11a068af802bd6fe2898fc1f48f282"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "75f60796b3ef60a50c2e2bec4c8d5667c15fb481d6868921ec8156b173213ae0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "048216c6ed9a8cee9c27b37a82a5eb7d618bbf88"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "dab3fe6e7defa81f434f657169b2c1e076affe540ca1d05edf98c1b4806e964a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0971721e7d0900d788d85ae7e5c5cbb57866e89b"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "40d0884bca871f6f3229780739411a4fb7b8f9ed665a2e32b7e522b53f803c49"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c01de7e506650fbf638ae404a37eb4b1935da71"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "1efdbde28f6ed8987a1b9f29dd7e9f6cbeacfec137388d8279a25657eec01d8f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa07c768c331df66d5386d2646f481d6ebdb5bad"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "8b8fc3469b4a7881b91dbee7b44b4bdfe8177351819525331f6872a52a87aced"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "246192edc8ff4e36d2e57aa40b83e25262fb7ee8"
os = "windows"

    [[GMP.download]]
    sha256 = "d2c3e7c3147cf61357509319915cb2f7b513de285657fa3b00228a74d501d152"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c32f08007a0d5fb5abba673a090103a1057b697f"
os = "windows"

    [[GMP.download]]
    sha256 = "f72ce81ea5d8b930b3eba17939e8422559552d61802595df75219da00c7769d8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54342369c9f2297eddfae47f4b8ff2880a131021"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "43077f7f18249526c7b4cfeb95b4200c5a6b8e20f0ea19481051f716370ff396"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a335b623ec121406e3b1d56a726cb54c2d36f0b"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "2fa00f87b14e33d746915f18065c23111478af83c940e65074bf58bf461a06e0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "776b19e227382ff3671570cf8b37695efc7cba43"
os = "macos"

    [[GMP.download]]
    sha256 = "4bb5a19589220eb03028258230eee14e580f9919584b06609713ccb97bd7d68e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f52e5981cbcb3e7ac50ba1c86ffb0a1ce0c368d3"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "60ddb2bf177fe468bb08aeaf622a2adbd35ae5623569c01d7e84ba1830da7ec5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39b8e3dea0a701983a8ae84a2c567e1c4e555c7a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "eb95f19cb29822cd71bbb5d4424e06224a4f8df544d957462348583efe4b0793"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df7463151a9a3e6a14df3798b14082ea34effcc7"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "8a91c5b50560ffbb63b743efa656e9fb3c0e90cba547487a556592fd4ae77995"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a57c634293a04b47c2da6d5f649b83f7c74044f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "b246533de187095e6e29fdcc2f68f8c52477356d5bc4a85ef7374294f7b66d12"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "c6dd1a5788f205dac339c5397d4fb01ec0680e2d"
os = "freebsd"

    [[GMP.download]]
    sha256 = "a9c57fd7f230bf16f2ea512ac4b0731beac0385767faa5cedcee44af9cb0e122"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f47e6e6d4278e8104309e8134848ad35e0a1777e"
os = "windows"

    [[GMP.download]]
    sha256 = "d91a61bb51c5fb3c4d73dce8c73eed26989f9ecfd83682de850a31225daaffaa"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9633307742879848e2363664e22183d1d99045c4"
os = "windows"

    [[GMP.download]]
    sha256 = "1865e37bef365c5470dd2bee13e1a6c077689dc2e4144a728a28e6c1f9a7aa23"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+6/GMP.v6.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
