[[GMP]]
arch = "x86_64"
git-tree-sha1 = "34d096e740ebd9534a42f8c83af702be654e6bd9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "ecaf8204d8b247582e67a1a08b024184feaafcb578785477a2a8493d7e8fb68f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "ff0744ea99b0891eef0d4411271bf4cb0fbe2b6b"
os = "macos"

    [[GMP.download]]
    sha256 = "12f21b2a0053e605917a5aee587a59960bb0c9ec2cbb283d179b7bb86b31cdd2"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-apple-darwin14.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "2ff1de3c8ca5e4ef721e102971297bc2c0399e2c"
os = "windows"

    [[GMP.download]]
    sha256 = "53444e4e577dfbede980163275605fc3ecc9ad723e25dfd9c87077d632f9650c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-w64-mingw32.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "c0b973280abf027a9d7faabe0c9ab6ffa43c5c9a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fbc2fca1d9e5a5f83fc5b1bac9d6718eb4b52533e6315a05fb81b0238cf9cca1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-gnu.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "bf7b1b4c0a697c6803ede9d67a22c6322eec118f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "55287ef03426b3f9e7a02ae6a8edb50c19e384e9f5f8ad30753635768368e104"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-musl.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "c6ab3415e18e02854ecce1239c93e23ed4d3aedf"
os = "windows"

    [[GMP.download]]
    sha256 = "7ee34522a51fa64a0c5832152b5716dec7555a76eb9534954fdd16aa17f49efe"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-w64-mingw32.tar.gz"
[[GMP]]
arch = "powerpc64le"
git-tree-sha1 = "1b471ad880cf60f8421c3584b4faad9402221b03"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b0b3c10be503a02cfb48d5e2e9522feb91a011e8ad410e3272e5069d43c075de"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.powerpc64le-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "c14e2823cf299ae1cabd483ab63f59c70b57a050"
os = "freebsd"

    [[GMP.download]]
    sha256 = "bff9ad7b07cb33ca69ea4645839611c7c24e08ed43e6e01c4d8f5b2d62871273"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-unknown-freebsd11.1.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "7cc4195459c46057dab9ac23b0919028146c02b0"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "59a87742baae9882b55d80c2d300df6e9c4f6cbf3885f8ed2538f5b1650da9d8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-musleabihf.tar.gz"
[[GMP]]
arch = "aarch64"
git-tree-sha1 = "1f4e2b3238bac23a13bbc3903f9a9ce12f5ea495"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "34ddd83b747e93900776d59876f1a18e621a58234733210a39943fcbb1eb9153"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.aarch64-linux-musl.tar.gz"
[[GMP]]
arch = "i686"
git-tree-sha1 = "50f9d24c026c4ec8f8b736070b1699b7e50da5a9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "2f4e891669b9ce548edda0ec92d09fd04796a0b88e09110afdf94c3275b23d03"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.i686-linux-gnu.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "1ec145fce5740d2c0992e960ddfb902d09bce5ad"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "361fb92419a6a81e4e2c2440b301df8b0a3adbbba75e31f4630c7455febd410e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.x86_64-linux-musl.tar.gz"
[[GMP]]
arch = "armv7l"
git-tree-sha1 = "6805cd2f50e55da5b8842f946aad95dddd3cdf78"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "6566f97bddb85adf339cee94fb0dab786f07954b07d126284426911ae93af964"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+0/GMP.v6.1.2.arm-linux-gnueabihf.tar.gz"
