[[GMP]]
arch = "aarch64"
git-tree-sha1 = "d82acf18377323e9f57724ee516514e6f5e78864"
os = "macos"

    [[GMP.download]]
    sha256 = "2bc2f20e9cfacfd8451b762360050db2c18ae630972c8ee7685a034fe571138c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "caf1db8de62c64178014166b89e3c546b4a997f4"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "f3a144f7b81a99026747e36dbb5d28d612d2c1af92e2e08b51df4a189bd982b6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31d817f4248ead6b783b4ead5cee293176ef0696"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "886a2409faca97c7193db517a2be780bc4c92853abb5eddc66ff71eb99a5f401"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d895824af260041ddf05fd0e71bb69f065712b8"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "4d803e339e27007719348aad8b296907955ae1237f5b4455ad88c0400d4d6ec6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "522dbd41bdeca48dfdaa337423a0cfc7e4f25329"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "19fd61c7178166c8c7687300e8ea93c9cfe74713e0aed6f41d8d87315b2557b3"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a4c320ae1fb10656368e8849564b15f59743150"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "69048489526987bb0297ce8043a1843c35981a7f11ef51804a9f855f50978454"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "459bfcc2f52af0c2810e4a2e4f251716b0a84c33"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "710007f686541abb8e37591f0a4f9329bd679764fc04c5a167b0bb70f802a943"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fe54d61d4a1a7595c6436ac3a5d3e1039364396"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "76464ff539c45c1b9a6403224aa1b609baf4773d0e52e265696b5c4db5937dd4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "461eeb840fb6f579c9de711621f6791e3454cfa9"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "3197a46c0df4aa75535f4ce4b14781439d835058d8c272e55d3132b232358e57"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a17727510925e088d9280b174e2c2ab7e7a1b48a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "55afe73b4c1acd4934b1132d4db2c51db66aee9cdb97873eeb9a3ef3247115a8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb19091172c3934c4c25d5781cf568d6917ff60d"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fe5dc26634906ae5a8f2cc631e6b5c45801b41056e58af43f4c83d8748c75e6c"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0865e755dda31b9cc9de4020d0d758faaa863cf9"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "804fe954b0ce1195f89311fef2b92b675b451001a105ba9cdf1233729df5d2be"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "692d67d5051138dd24c87ad998a174d2c436e2ba"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "5e754d9f12988152931d35d333ab03f28eb4bc43154b2f78400c9dda160df2d5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91b40eaa5570c98fec66c208a3ce1c6f01dfc9b0"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "614a40a7b17dba70baa5c937c4608a0854b10d55754e1168653dbe50e31c39e0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8b291492394130bdddcecdc27cc282fa4c6f8f4"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "0bd858056fc5df64a804b8cf04005beb72406114dc4270f03c903ee4c9888bde"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db61d80e9c0bfabc4aa42a20ddc05ac5b24167df"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "02a143760a225abc963999bd4985f7db62a27169d079a9cc7affdd1e01ba720b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "690d6caf5be54b4e2ac805479fe2a3f7b7410221"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "b7209287a5a1d08b19d663f54bcf277b076b70acecb8b6ccd54b19db790b9785"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17da92343b20baddfccad2a2d23dd882e48d1f35"
os = "windows"

    [[GMP.download]]
    sha256 = "74b022d327c42807f7a68814cf982f21339dab11194bf27176843436148545a5"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06f8341bd31362073879f9d3e4c7a2ef213a485d"
os = "windows"

    [[GMP.download]]
    sha256 = "c712eca49bff594200c5878d7976f5742d3bcec8c81400b21adbc781ace87096"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67451014f5aedbd111d1d0d444b9398d6bff3e6e"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "1b08f9a4847421e6e4275ab147667b4b66a4ce4bd1810ac3770498837cb1f914"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d54fb351038bba501bf53b80223c3d5bdaee37bf"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "d9bfb22a28ad9fdb1a40b4b39d72778fdd469b5bed6f699034e3c07980006439"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "e3766590382555a3ab12cb40abdc4037a89e0124"
os = "macos"

    [[GMP.download]]
    sha256 = "6f288bea8f2299fbfd09dedb2193622971927404dbad48ffdf0af7e3ac70fe7d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78a0e3d9ae8f266e6e7ec2801cdf7875847df410"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b77059123cfe5b7761d772254be4cf5adcc88471043d1d88783a3104a65aa628"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "866530790eff8c1b3360a00136be6635764c1cc2"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "9d8bb9322afb1f70147fe2570cdaff4a4927118d2c6ceed817a8d631079fe8ba"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ac05b44657b5ae3dfb9c37f9c0b77afb5be066f"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "7cce218e06fcb6bd39e4a9395bb2f607e7f89e13cda358dc0d5429fa93c523df"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68221bc0dd1159f25a0dd77ed6b1048fe0ec526a"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "5a1edf4e7242a6d8dbae90f54449f4b9c503fc5cd81e27e93ee1aed60ace6817"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "beab65767cdb7f4094f2d67fbbb64bc622f5ce4e"
os = "freebsd"

    [[GMP.download]]
    sha256 = "93b3488a7b7c76c674ceb4e8ad7d3dae12612636517371672b05d524a10e9bbb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb1f3a4f0ba1582cf43e0942e642dcda0838232e"
os = "windows"

    [[GMP.download]]
    sha256 = "10a25e04b6a6d20ac0494029d08a51bcf27f4aa53d8d867479c45b438748395e"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b68fc0b87b01b3e629ca603a60fc67b35a1b9fa"
os = "windows"

    [[GMP.download]]
    sha256 = "90f3fed741b679df5479483ab58a9d1fdcb7aad440468dc99790edf8c956e0df"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.1.2+9/GMP.v6.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
