[[GMP]]
arch = "aarch64"
git-tree-sha1 = "18d606879940c45c92829d6180e6c3ed78c1e8e4"
os = "macos"

    [[GMP.download]]
    sha256 = "9f8af636999b6b29f5cb161445e73f4b0cb09787e5d1e671f6ee36ad130cc1ef"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.aarch64-apple-darwin.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "438763d0a0d11ca36b300e9324b99a83b725adf9"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "1d317eb5aa6a0872f807c7f3a5bac141cfc607c6e5b20806c668983199f81e90"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b804693dba33bda298f5f890b9afd2600db2f546"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "fcd9aba37abb579427b39d41f50f0175dff087edd12be81c4251592422f1f3c9"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69310c54157613a7e35c8e6d4938d5600cbf3048"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "b90f4d3a7546ffd437440c2eda91e031aaaaecb280c11d0a619130801aa29fad"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eee3abb987916d9c01ca5fbe64ab199f53ddb84"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "b4ab45e7b07b99e3adec944382d66ebc7a19973fd291696c076be8409e7d9c81"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5b3aa03ec084ff4dfbb487627747ef8e07db7db7"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b72e9e7ce28eae4e9c4888a6b98627a74cb9fc7252c9807e516868b0163d05dc"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "846ff0fe875c1ed45b4aef5b97cbe2cf860daa3a"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "72f85534c35197adf85ca817264f8ac87ccef13a6f20e8c12c881c44ee89e098"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96708d222bc7767b241604a35fa6358bc38c2938"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "24ecf1cca679e385dbd84a69e00975a7e4c19110693fab9e91e7a6991a6fccf4"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca5e84c59416facfe091b21c9773aad771f7d27d"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "7463fdd77d169bbc2563ddd28feff22faf4b73e3415ee0ec91f3f783f0bb4f44"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d50ce369d4ccdb62f7a8b28141026e4481119cb4"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "77fc26147536c31c4baef1fc0300eb6092ae8b98f1c9875c7ceb7ddfc6f51041"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa620d4b95fef06716ded7eb77525ce0420da3ab"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "9ef7fddb5fc28f9155b61b2dc21fde987e4783f9269b93e1de45bcb5cd18939f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7977ae5c0f69de7f00f380c43c96c7e0881890f2"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "fc6a924b508a45b9a8029b87905749c5d4c62c114de26d2c413cb948ba6d61eb"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GMP]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e6dc5c976cadcb5f20848e2b71e09da43d4506d"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "b70b4940a0c7c3c2efd97da5eadf824a90d59e0aaba61699b5b478d2b290144a"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ff7794165d9cc3bfad4852581d1fea1d992f942"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "9832fd124db5eae1172d107b93510901b764dae189f7718fe0f1050bd2810689"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.i686-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5764e6ba028d2f7e71d620a9ab6b1452bd451769"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "c500188b6feae7715d17f36bb40a453d47f3da7bba2601c27cb59abbc1014f3f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.i686-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "053386407a38904d54936c7c3b8a6cf8491897d5"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "39fcf9f4ccf3ed3747c33652dac886f946c4e2c1806b99f0b6896df9482bb51f"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.i686-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ddf6cc79ec510c42671f8adcbf61139c34b84c2"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "8af93d3c18e0ecb7eda27b534ddf5e21f7dfc84e677e7492312fbc7ec6d9175b"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.i686-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "736bf4d60e8310bd0705974b9c3f9f4db3181b4b"
os = "windows"

    [[GMP.download]]
    sha256 = "1ab9290b3cbf03eb6b39b7892d114dc24bd1e0702a09aa54a8f2e37b4fd1d181"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52871f92cd7fdd97c56424b9b0988cba7305155c"
os = "windows"

    [[GMP.download]]
    sha256 = "fc70d2d2a0e7c02663c31bf61fa02be0acf3d113e3bc5394597b2f0bfe1879c1"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "286e61e5d87b6efe1efd030878cc6d0c138c27b0"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "b1f7536f0045a7db5cf2bbb6434b809a57d18e58b8aa36aac53b4a217f9f35fe"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5cc9a7333a41bf9565cb58decf34c5778a832b2"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "61b870a74f9c407b30ac82f06e9c52cded18eefb5cca54d725d7c0f312784166"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "e0dd8107d139685a1e2fc9778c83b2ce9748a21d"
os = "macos"

    [[GMP.download]]
    sha256 = "809f3767c654604895abf8fcc7d967a21cf1be391a56a9b206d2d19d110dff53"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.x86_64-apple-darwin.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adce8608805da098504a2d74d1cb3fb2877b53d8"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "924a468a16f5f1d6bada463afb6481f6e2c9834e90deed0d088d688745c932d6"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6912b17607ad3f04f3faaab3e3918181ffca515"
libc = "glibc"
os = "linux"

    [[GMP.download]]
    sha256 = "8eb67597ce901a462f7acfb634ef7fe7433011e80b8886139bf2549c3ba624a0"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25e21b2dd3faf6b48c812e4d06dc8ba52404be08"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[GMP.download]]
    sha256 = "73594c84194047f9e58bc577bd58abd252b52b56c9f1759c916ab4f49ee14888"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.x86_64-linux-gnu-cxx11-sanitize+memory.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec6aa9d7df206de06280addabe495b32b11b0c24"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "c960e056377bf1d0329140f287fc7844d63746380d674b0eb4c5936690215145"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca6965c5231c6d53948d281bc937aea24c88d626"
libc = "musl"
os = "linux"

    [[GMP.download]]
    sha256 = "ef09c9d7a265e0762585b41b02fc3f0f29132a571220fa92397607ee84482164"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[GMP]]
arch = "x86_64"
git-tree-sha1 = "b2762b71c8153e0b0e747133b57d240cdb31f737"
os = "freebsd"

    [[GMP.download]]
    sha256 = "e6a58afa523e5e94f15cc582376c204753e7c332ca1f0adbad87e8a4d1a475b8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.x86_64-unknown-freebsd.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a67de0ae9999d823cdd888bb60afdde544ddec7a"
os = "windows"

    [[GMP.download]]
    sha256 = "d32ee62013413e9aa794c34033aa04246eeb0abbbcc7647281a73affe4b6e54d"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[GMP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a3d40c40b075a8c15973fd957f6a539471979e2"
os = "windows"

    [[GMP.download]]
    sha256 = "bfeb536ca90a1423bd6843cd13898651555f730d36c0a8735b20631618513fd8"
    url = "https://github.com/JuliaBinaryWrappers/GMP_jll.jl/releases/download/GMP-v6.2.1+4/GMP.v6.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
