# Autogenerated wrapper script for GMP_jll for x86_64-apple-darwin
export libgmp, libgmpxx

JLLWrappers.@generate_wrapper_header("GMP")
JLLWrappers.@declare_library_product(libgmp, "@rpath/libgmp.10.dylib")
JLLWrappers.@declare_library_product(libgmpxx, "@rpath/libgmpxx.4.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgmp,
        "lib/libgmp.10.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgmpxx,
        "lib/libgmpxx.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
