# Autogenerated wrapper script for GMP_jll for x86_64-w64-mingw32-cxx03
export libgmp, libgmpxx

JLLWrappers.@generate_wrapper_header("GMP")
JLLWrappers.@declare_library_product(libgmp, "libgmp-10.dll")
JLLWrappers.@declare_library_product(libgmpxx, "libgmpxx-4.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgmp,
        "bin\\libgmp-10.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgmpxx,
        "bin\\libgmpxx-4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
